### ISSUE TITLE
Première version du site en ligne selon le gabarit

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#1]
"The Charity" (https://colorlib.com/wp/template/the-charity/) a été sélectionné par Yanic.

**Comment by yanic1665** [comment]
Est-ce normal à ce stafe-ci que je ne puisse télécharger aucun numéro du Bulletin en cliquant sur les numéros dans la page http://aphcq.dcycleproject.org/bulletin.html? Un message d'erreur apparaît plutôt.
