### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#12]
Le logo est dans google drive, il faut changer le H vert pour un H orange.

**Comment by alberto56** [comment]
Ceci est prêt au http://aphcq.dcycleproject.org @yanicviau SVP fermer ce billet si c'est OK!

**Comment by yanic1665** [comment]
Sauf erreur, je croyais qu'on avait convenu de garder le nom complet dans le logo. Remarque, je n'ai pas de problème à l'enlever, ça fait plus dépouillé. Mais dans ce cas, où le nom de l'organisation apparaîtra-t-il dans le site, et en particulier dans la page d'accueil?

**Comment by alberto56** [comment]
Le logo contient le nom, mais il serait trop petit dans sa forme actuelle. On pourrait le mettre dans l'espace blanc, dans la même police de caractères que le menu?

![Screen Shot 2020-03-19 at 11 47 19 AM](https://user-images.githubusercontent.com/808265/77085975-74ff6080-69d7-11ea-926c-b356ca3e3f9e.png)

**Comment by yanic1665** [comment]
Oui, d'accord avec ta suggestion. Dans tous les cas, j'aurais besoin pour nos archives d'une copie du fichier d'image que tu a créé (à savoir le logo avec le H en orange), dans la plus haute résolution possible. Si possible, j'aurai besoin aussi du logo intégral (acronyme et non compelt) également avec le H en organe, si tu l'as.

**Comment by alberto56** [comment]
Le logo est au http://aphcq.dcycleproject.org/images/logo.png -- toutefois étant donné que le nom complet sera à côté, il ne figure pas sur l'image du logo.

**Comment by yanic1665** [comment]
Parfait, merci! Yanic

Le dim. 22 mars 2020, à 08 h 45, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
http://aphcq.dcycleproject.org
