### ISSUE TITLE
Liste des bulletins

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#13]

**Comment by alberto56** [comment]
J'ai pris les bulletins du google drive, je les ai comprimés pour qu'ils téléchargent plus vite sans compromettre la qualité et tu pourras les voir dans l'onglet Bulletin de http://aphcq.dcycleproject.org

Comme pour les autres éléments du site, on peut changer cette liste [dans le document _config.yml](https://github.com/aphcq-association/site-web/blob/master/docs/_config.yml#L108-L115).

Et les bulletins eux-mêmes sont dans [le répertoire bulletins](https://github.com/aphcq-association/site-web/tree/master/docs/bulletins).

Le texte [peut être modifié ici](https://github.com/aphcq-association/site-web/blob/master/docs/bulletin.html).

@yanicviau laisse-moi savoir tes premières impressions et ce qu'il reste à faire.

**Comment by yanic1665** [comment]
Albert, je viens de tenter de réorganiser la liste des numéros dans la page
consacrée du Bulletin, afin d'inverser leur ordre de présentation pour que
le splus récents apparaissent en premier, mais aussi pour créer des
sous-sections par quiquennat (des reegroupements 4 ou 5 volumes) pour aérer
un peu la liste.  Les changements ont bien été enregistrés dans
https://github.com/aphcq-association/site-web/blob/master/docs/_config.yml,
mais j'ai reçu plusieurs messages d'erreur et ces mênes changements
n'apparaissent pas dans la page web mise à jour. Quelle serait la cause du
problème?

Yanic

Le jeu. 19 mars 2020, à 12 h 24, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
La façon d'organiser les fichiers était trop limitée, et n'était pas pensée pour les catégoriser par "section". J'ai tenté de le faire mais le résultat n'était pas trop intuitif.

J'ai donc refait la page bulletins en format "markdown" plutôt qu'en format yaml, et maintenant la page bulletins fonctionne comme n'importe quelle autre page, voici le résultat:

* dans le code: https://github.com/aphcq-association/site-web/blob/master/docs/bulletin.html
* sur le site: http://aphcq.dcycleproject.org/bulletin.html

**Comment by yanic1665** [comment]
Est-ce normal à ce stafe-ci que je ne puisse télécharger aucun numéro du Bulletin en cliquant sur les numéros dans la page http://aphcq.dcycleproject.org/bulletin.html? Un message d'erreur apparaît plutôt.

**Comment by alberto56** [comment]
Non c'était un bogue, merci de signaler. 

SVP confirmer que tu peux télécharger tous les bulletins au:

* http://aphcq.dcycleproject.org/bulletin.html

et aussi au:

* http://www.aphcq.ca/bulletin.htm

tu peux ensuite fermer ce billet

**Comment by yanic1665** [comment]
Ça marche, merci!
