### ISSUE TITLE
Documenter les formats de photo

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#14]

**Comment by yanic1665** [comment]
J'attends de connaître les mesures requises pour les photos afin d'envoyer une commande à mon collègue Sylvain pour qu'il puisse éditer et retoucher de nouvelles photos. Je devrai lui laisser quelques jours alors le plus tôt, c'est le mieux.

**Comment by yanic1665** [comment]
Sur la base d'un calcul manuel (à partir d'une version imprimée d'une des photos), j'estime le rapport hauteur / largeur comme étant   1: 2,288 (par exemple: 5,9 cm de hauteur par 13,5 cm de largeur). Je viens fournir ces précisions au monteur des photos, Sylvain, en lui demandant de laisser une petite marge au cas où. Je lui donne jusqu'à marid midi pour tenter retucher trois photos des destinées au carrousel de la page d'accueil (au moins une des trois photos potentielles devra rempalcer lapremirèe photo actuelle du carrousel) , en espérant que ce sera suffisant pour lui. Je ferme donc ce billet.

**Comment by alberto56** [comment]
J'ai documenté la taille exacte dans la section "taille des photos" de http://aphcq.dcycleproject.org/guide-admin.html (en pixels)

**Comment by yanic1665** [comment]
Super, merci Albert! Je transmets ces précisions à Sylvain, qui m’aide avec les photos.

Yanic



Yanic

**Comment by yanic1665** [comment]
OK, merci Sylvain,Je comprends bien ta situation. Fais ton possible.

Voici quelques précisons supplémentaires à propos de ce que nous aimerions,
dans l'idéal (je reprends ici les titres des fichiers d'images que je t'ai
envoyés récemment dans deux courriels):

   - Exécutif APHCQ: format bannière (c'est déjà mal mal comme ça)
   - Atelier congrès St-Jérome: grande taille
   - Hôtel de ville: grande taille idéalemetnt (sinon,  petit taille c'est
   OK)
   - Public d'atelier: grande taille idéalemetnt (sinon, petit taille c'est
   OK)
   - Réunion d'nfo St-Jérôme: grande taille
   - Conférencier: grande taille

Yanic
