### ISSUE TITLE
Problèmes avec la mise en ligne des textes 

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#15]

**Comment by yanic1665** [comment]
Je viens de modifier le texte de la boite orange "Congrès 2020" dans la page d'accueil afin d'annoncer l'annulaiton de l'événement.  Le texte a été sauvegardé  dans la page "Code"' il mais n'apparaît pas dans la verison mise à jour du site, et j'ai reçu un message d'erreur (dont je ne nsais plus le contenu, j'en ai trop reçu ce soir!). Que faire?

J'ai aussi voulu modifier le texte principal dans la page "Congrès 2020", mais je ne retrouve pas le lien correspondant dans la page https://github.com/aphcq-association/site-web/tree/master/docs. Comment puis-je y accéder?

Voici le texte que je voulais insérer dans la page
http://aphcq.dcycleproject.org/2020/03/10/congres-2020.html:

" AVIS : En raison de la pandémie de COVID-19, le Congrès 2020 de l'APHCQ prévu les 27-28-29 mai 2020 au Collège De Maisonneuve à Montréal doit malheureusement être annulé. 

Le comité exécutif de l’APHCQ souhaite organiser une journée d’étude portant sur le nouvel énoncé de compétence d’initiation à l’histoire (en cours de révision) ainsi qu’une assemblée générale dès que les circonstances le permettront. D’autres détails suivront. "

**Comment by yanic1665** [comment]
J'ai tenté en vain de modifier le texte de la "Description courte" de l'APHCQ. La nouvelle phrase a été sauvegardée, mais la mise à jour de la page ne se fait pas. 

Voir ligne 7:
https://github.com/aphcq-association/site-web/edit/master/docs/_config.yml

**Comment by yanicviau** [comment]
Queles autres commentaires en rappel (on avait soulev ce spoins lors de notre discussion:

- Il manque une 6e option dans le bandeau de lapage d'accueil, soit l'option  “ ENG” (pour English), ainsi qu'une nouvelle page correspondannte “About APHCQ” pour accueillir le futur texte en anglais.

- Carrousel photos: la première ligne du titre “Congrès de l’APHCQ 2020” est coupé dans l’app mobile (manque d’espace). 

-Rubrique “Infos” (et page correspondant) à enlever de la page mobile pour assurer uniformité avec la version web

**Comment by alberto56** [comment]
J'ai remarqué deux problèmes qui empêchait la mise en ligne, j'ai réparé ça au https://github.com/aphcq-association/site-web/commit/f9a2772a232cf35cf5d54c0812d82f54f37613bd

Noter: (1) J'ai mis texte: "Avis: Annulation" plutôt que texte: Avis: Annulation, car si la valeur du champ texte contient un "deux points", le système exige que ce soit entre guillemets.

(2) pour grouper les bulletins par section, je vois ce que tu veux faire, et je l'ai réglé, voir http://aphcq.dcycleproject.org/bulletin.html, toutefois on ne peut pas le faire comme tu l'as fait, ça va empêcher le site d'être généré.

**Comment by yanic1665** [comment]
Merci bien!
