### ISSUE TITLE
Méthode pour insérer des hypersliens dans un texte avec Markdown

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#16]

**Comment by yanic1665** [comment]
Comment associer un extrait de texte dans une page  à un hyperlien avec Markdown? J'ai beau cherché sur le web, mes tentatives ont été infructueuses.

J'ai trouvé ceci, mais je n'arrive pas à comprendre...
https://daringfireball.net/projects/markdown/syntax#link

L'exemple dan sle guide Github ne me semble pas clair non plus (en tout cas, je l'ai suivi et ça n' pas marché, j'au plutôt reçu un message d'erreur): https://guides.github.com/features/mastering-markdown/#Links

Voici les liens internes que je souhaite insérer: 

- Page "Qui sommes-nous?" (http://aphcq.dcycleproject.org/apropos.html): les expressions "Bulletin d'information" et "Congrèsa annuel" devraient pointer vers les pages correspondantes de notre site. 

Et  voici les liens externes que je souhaite insérer:

- Page du Bulletin (http://aphcq.dcycleproject.org/bulletin.html): expression "Dépôt des publications numériques"  mettre en italiques et à lier à la page 
http://numerique.banq.qc.ca/patrimoine/details/52327/2512509

- Page "Qui sommes-nous?" (http://aphcq.dcycleproject.org/apropos.html): expresssion Coalition pour l'histoire" à lien à la page http://aphcq.dcycleproject.org/apropos.html

**Comment by alberto56** [comment]
Salut @yanicviau 

voici un exemple concret avec:

> Page "Qui sommes-nous?" (http://aphcq.dcycleproject.org/apropos.html): les expressions "Bulletin d'information" [...] devraient pointer vers les pages correspondantes de notre site.

C'est comme ça que je l'ai fait:

https://github.com/aphcq-association/site-web/commit/00857ce698d69dd391339456057ce10727603ae4

En rouge, c'est avant (sans lien), en vert, avec le lien, 

SVP me dire si t'as besoin d'aide encore avec ça!
