### ISSUE TITLE
Liste des modifications à apporter à la structure et la mise en forme du site (RAPPEL)

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#18]
* [x]  1. Bandeau: mettre  la mention "Pour nous contacter" en minuscules et non en majsucules (jsute avant la mention du courrie).

* [x] 2. Carrousel photos: deux titres sont coupés dans l’app mobile car ils occupent trois lignes au lieu de deux:  “Notre congrès annuel", "Suivez-nous sur Facebook". Par ailleurs, dès qu'un titre occupent plus d'une ligne, ce qui est le cas de 4 titres sur 5, la case "Action" en organfe qui se trouve en dessous est également amputée et donc difficilement lisibles dans la version mobile. 

* [x] 3. Dans la version mobile, i n'y a pas de flèches qui permettent aux internautes de voir que les phtos du carrousel peuvent être changé

* [ ] 4. Dans la verison mobile,,l'icône du menu en haut droite est presque invisible, étant "noyée" dans le nom de l'APHCQ qui se trouve dans l'entête.  DÉPLACÉ.

* [x] 5. Vérifier que le code correspondant  aux quatres hyperliens insérés dans la page en anglais par Yanic sont fonctionnels (lignes:  24-28-30-32): https://github.com/aphcq-association/site-web/blob/master/docs/english.htm

* [x] 6. Le texte principal dans chaque page apparaît en gris pâle, ce qui en rend la lecture difficile. Il faudrait envisager une police de couleur plus foncée, et modifier du mpeme couo la couleur des mots reliés à des hyperliens.

* [x] 7. Il manque une 6e option dans le bandeau de la page d'accueil, soit l'option  “ ENG” (pour "English"), qui doit renvoyer à la  nouvelle page correspondannte “About APHCQ”.

* [x] 8. Rubrique “Infos” (et page correspondant) à enlever de la page mobile pour assurer uniformité avec la version web

* [ ] 9. Indiquer dans le site les conditions d'utilisation du contenu du site (idéalement, avec droits restreint restreints pour les photos (sur demande uniquement), car elles appartiennent à des tiers. DÉPLACÉ

* [x] 10. Édition du logo (suite et fin: voir la tâhce créée à cet effet).

* [ ] 11. ~Gestion des photos: remplacement requis de certaines photos et modification de l'ordre de photos dans le carrousel. Voir la tâche spécifique créée à ce sujet pour les détails.~

**Comment by yanic1665** [comment]
La tâches suivante vient d'être ajoutée dans la liste: 
"Vérifier que les quatres hyperliens insérés dans la page en anglais sont fonctionnels (lignes: 23-27-29-31)."

**Comment by yanic1665** [comment]
@alberto56 , les cinq premières tâches de la liste ont été ajoutées ou renaniées à la lumière des derniers changements et vérifications faites par Yanic.

**Comment by alberto56** [comment]
Pour les liens vers des emails, il est important de mettre le format "mailto:...", comme [ici à la ligne 32](https://github.com/aphcq-association/site-web/commit/0fcb1d97a9f800b4efd3d2df56666d2f5fb8334a). Le reste des liens english c'est ok comme tu peux voir au http://aphcq.dcycleproject.org/english.htm

**Comment by alberto56** [comment]
Les points 2, 3, 4, et 9 sont dans des nouveaux billets #36 #37 #38 #39 

Je mets donc ce billet dans la nouvelle colonne "besoin d'approbation"

**Comment by yanic1665** [comment]
Question niaiseuse (et non urgente): pourquoi les pages du site se
terminent par ".html" mais que la page en anglai se termine par ".htm"?

Yanic

Le lun. 30 mars 2020, à 13 h 11, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
En fait les deux sont acceptables, html et htm. Ce serait plus propre de s'en tenir à un seul standard toutefois; Si tu changes, par exemples, english.htm pour english.html, assure-toi de le changer aussi ici: https://github.com/aphcq-association/site-web/blob/master/docs/_data/sections.yml

...ou, encore mieux, utilise notre rutilante nouvelle interface administrative.

**Comment by yanic1665** [comment]
OK, merci. Je n'ai pas de préférence, c'est juste que lorsque je cherchais
à accéder à la page de façon intuitive l'autre jour (alors que celle-ci
n,Était pas visible depuis la page d'accueil), je m'étonnais que ça ne
marche pas avec "html").

Le lun. 30 mars 2020, à 16 h 15, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
@alberto56  J'ai coché les tâhces terminées. Sauf erreur, il ne reste plus que les tâches 4 et 9.

**Comment by yanic1665** [comment]
Tâches #4  et #9  déplacées dans #35  ou aulleurs afin de réduire les listes de tâches en une seule (elles sont donc toujours à faire mais je ferme ce billet).
