### ISSUE TITLE
Problèmes avec deux modificaitonsn dans la page "Qui nous sommes".

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#19]
https://github.com/aphcq-association/site-web/blob/4291be56f81aeb673afcd7b5f4baf1ae6c2b1d17/docs/apropos.html#L16

Mes modifications récentes à la ligne 16 (ajout d'un liens vers un fichoer pdf nouvelleemnt ajouté) et à la ligne 18 (effacement d'une tentative d'insertion de photo de ma part, finalement annulée) n'apparaissent pas dans le site.

**Comment by alberto56** [comment]
Le dernier changement dans https://github.com/aphcq-association/site-web/commits/master à un crochet vert donc ça devrait être bon, j'ai aussi documenter comment déboguer ailleurs, si tout est OK svp ferme ce billet
