### ISSUE TITLE
Formation en personne

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#2]
Personnes intéressées par la formation (à ce jour): Yanic, Christian, Paul, Julie

À faire: 

* [ ] Formation à donner (8 avril, 19h00,Zoom).
* [ ] Guide d'administration du site à finaliser et partager.
* [ ] Sauvegarder et archiver l'enregistrement vidéo de la formation.

**Comment by yanic1665** [comment]
La liste des participants è la formation est la suivante

Personnes intéressées par la formation 
- Yanic
- Paul
- Julie 
- Christian

Un appel à tous a été lancé au sein du comité exécutif le 24 mars. Nous pourrons nensuite faire un sodnage pour trouver le mielleur moment.

**Comment by alberto56** [comment]
Pour ajouter des comptes, il faut le username et le mettre ici:

![Screen Shot 2020-03-24 at 5 33 05 PM](https://user-images.githubusercontent.com/808265/77479267-d8cdc300-6df5-11ea-9a57-64f23fe98d9e.png)

**Comment by yanic1665** [comment]
@alberto56 Sur quelle plateforme ou avec quelle applicaiton proposes-tu d enosu donner la formaiton de 2heures à distance?

**Comment by yanic1665** [comment]
@alberto56 Convenir d'unesolution technologique pour tenir la rencontre en mode virtuel.

**Comment by yanic1665** [comment]
@alberto56 Je souhaieteria alimenter et modifier le guide d'admistraiton du site en ligne avant la formation de 2 heures,, afind d'y intégrer les éléments consignés dans le document suivants:

https://docs.google.com/document/d/13Inihw7bXeSPndsLqAqtF_xzhsL-Y-LSToGo9lZjzAE/edit

Au préalable, j'aurais besoin que tu  : 
1.  en valide le ontenu  (forme et fond) pour éviter es erreur;
2. fassen un survol des enjeux à régler (indiqués en marge);
3. me porpsoe une procédure simple rpouvoir insérer ces éléments dans le guide en ligne, en procédant par copier-coller, et pour modifier la mise en page du guide.  Par exemple, un  copier-coller d'une adresse de site prevenant d'iun fichier Word  ne fonctionne pas.

**Comment by alberto56** [comment]
Ce plugin permet en principe de convertir de Google Docs (format fermé et propriétaire) à Markdown (format ouvert): https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607

Je ne l'ai pas toutefois testé.

Si tu veux je peux mettre ton contenu sur le site et l'y corriger directement, laisse-moi savoir.

**Comment by yanic1665** [comment]
@alberto56  Je viens de terminer la mise  jour du guide d'administration du site (fusionnant ta version et ma version), mais il reste quelques petits enjeux à régler et des libellés à valider:
https://docs.google.com/document/d/13Inihw7bXeSPndsLqAqtF_xzhsL-Y-LSToGo9lZjzAE/edit#

Je me suis installé le module d'extension suggété (doc to markwdown) mais au moment de faiee la conversion, le text en Markdown est bien apparu et je devais ensuite faire un copier- coller, mais un message d'avis est aussi apparu pour dire que certaines images poruraient causer problème.  Il y a vait aussi de soptions à cocher (voir capture d'écran). 

J'ai laissé tombé .

Pourrais-tu STP:
* [ ]  1. Régler les passages en jaune dans Google Docs (et si j'ai mal exprimé certaines idées ailleurs, n'hésite pas à modifier le texte) ;
* [ ] 2. faire la conversion en Mardown et mettre à jour la page ?

![Capture d’écran, le 2020-04-04 à 00 16 33](https://user-images.githubusercontent.com/61343142/78418612-c7619380-760b-11ea-8214-fbc22cbf0ef7.png)

**Comment by yanic1665** [comment]
@alberto56  D'après le sondage, trois personnes souaite participer à la formation: Paul  (président0, Julie (trésorière) et moi même. Tout le monde est disponible aux 4 dates porposées: 8, 9, 13 14 qvril 2020 à 19h. 

1. Quelle est ta préférence? Je propose qu'on arrêt un plan A, le 8 ou le 9 avril, ainsi qu'un plabn B le 13 ou 14 avril au cas où un un impréviu surviendrait (le plan B, on pourrait le garder entre nous deux).

2. Comment allons-nous faire la rencontre, sur le plan technique? Je propose Zoom, et si cela convient, il faudrait que tu l'installes et te familiraise avec la fonction  partage d'écran: https://support.zoom.us/hc/fr/articles/201362153-Comment-partager-mon-%C3%A9cran-

Je pourrais convoquer le réunion sur Zoom, mon compte de prof permet (actuellement de dépasser la limite de 40 minutes  pour les rencontres de plus de trois personnes. 

Yanic

**Comment by alberto56** [comment]
OK pour Zoom, je connais déjà.

OK pour plan A jeudi 9 avril.

OK pour plan B mardi 14 avril.

Rappelle-moi les heures SVP.

**Comment by yanic1665** [comment]
OK, noté.
C'est de 19h-21h (on fait ça en soirée à cause de Julie qui a des enfants).

**Comment by yanic1665** [comment]
@alberto56 En prévision de la rencontre de formaiton de jeudi prochain 19h, peux-tu me dore si tu es à l'aiseavec la fonction de partage d'écran danzs Zoom, et si tu as besoin de faire test ave cmoi avant)? Je tiens pour acquis que le partage de ton céran sera nécessaire et apprécié des participants.

Par ailleurs, as-tu une objection ce que je filme la formation (comme outil pour le futurs bénévoles de l'Association)?  Penses-tu qu'on va se partager des renseignements confidentiels?

**Comment by alberto56** [comment]
@yanic1665 je fais souvent des partages d'écran avec zoom, donc pas de problème.

Pas de problème pour que tu le filmes et partages. Par principe Zoom n'étant pas sécurisé, j'évite de partager des infos confidentielles.

**Comment by alberto56** [comment]
@yanic1665 Mis à part #43, pourrais-tu me dresser une liste définitive de ce qu'il me reste à faire d'ici la formation?

**Comment by yanic1665** [comment]
Ce qui resterait à faire selon moi en prévisoo d ela formaitonde demain, si le temps le permets:

#6 Éliminer l'option de paiment teste dans Paypal

Gérer mes trois nouveau billets, créés è la suite d'un dernier survol du site:
 #57 Accès à la page Facebook dans un omglet distinc
 #58 1ere photos du carrousel de la page d'accueil lente à télécharger 
#59 Photo d'accomapagnement dans la page du Bulletin à réorganiser ou changer
#60 Adresse visible du site dans la barre d,adresse.
