### ISSUE TITLE
Mes ajouts récents aux lignes 11 et 13 ne s'affichent pas dans la page "Bulletin".

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#20]
https://github.com/aphcq-association/site-web/blob/e4f7e112970d5291eaa6f157e425f33155c09c0f/docs/bulletin.html#L11

(voir ligne 13 également).

**Comment by alberto56** [comment]
Le dernier changement dans https://github.com/aphcq-association/site-web/commits/master à un crochet vert donc ça devrait être bon, j'ai aussi documenter comment déboguer ailleurs, si tout est OK svp ferme ce billet
