### ISSUE TITLE
Ma modification récente la ligne 10  ("des professeurs") n'apparaît pas dans le site .

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#21]
https://github.com/aphcq-association/site-web/blob/d755d6dcf1e801e8fc4ec0d701a967033970c346/docs/apropos.html#L10

**Comment by alberto56** [comment]
Le dernier changement dans https://github.com/aphcq-association/site-web/commits/master à un crochet vert donc ça devrait être bon, j'ai aussi documenter comment déboguer ailleurs, si tout est OK svp ferme ce billet
