### ISSUE TITLE
Ma modification récente la ligne 7  ("des professeurs") n'apparaît pas dans le site .

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#22]
https://github.com/aphcq-association/site-web/blob/e9500468fa7fe5467be35700012e83c2b3d923f7/docs/_config.yml#L7

**Comment by alberto56** [comment]
Salut @yanicviau j'ai fait un petit guide administratif du site que tu peux trouver au http://aphcq.dcycleproject.org/guide-admin.html ou en cliquant sur "Administration du site" au bas de n'importe quelle page. Je t'invite à visiter la section "Déboguer un problème avec le site" qui explique comment trouver la source d'un problème de site qui ne se regénère pas. Dans ce cas, c'est relié au changement https://github.com/aphcq-association/site-web/commit/9bc166c6a38d0fbe7b50a6cd2d7b4d6f5f5a5a5e que j'ai depuis réglé. 

La courte description devrait marcher maintenant, SVP fermer cette tâche si c'est le cas.

**Comment by yanic1665** [comment]
Merci énormément! je sauvagrde l'info pour la formation future de mes
collègues. Je ferme le billet


Le dim. 22 mars 2020, à 12 h 38, Albert Albala <notifications@github.com> a
écrit :
