### ISSUE TITLE
Ajouter un lien vers les statuts et règlements sur la page "Qui sommes-nous?"

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#23]

**Comment by alberto56** [comment]
Salut @yanicviau j'ai remarqué dans [ce changement](https://github.com/aphcq-association/site-web/commit/9bc166c6a38d0fbe7b50a6cd2d7b4d6f5f5a5a5e) que tu as tenté, selon ce que je comprends, d'ajouter un lien vers vos statuts et règlements sur la page Qui sommes-nous. 

Il faut éviter de modifier la structure de _config.yml; on peut y changer des champs et ajouter des infos selon une structure identique à ce qui existe, mais tenter de faire des changements va souvent causer un bris du site car la structure de _config.yml est très particulière.

[Voici comment j'ai réparé ceci](https://github.com/aphcq-association/site-web/commit/a6fa474c64cc171a782c2020c826e6c1023597a3), tu peux voir le résultat au http://aphcq.dcycleproject.org/apropos.html

Quelques notes:

**Note 1**: J'ai ajouté ce code directement à la fin de /docs/apropos.html:

    [Voir nos statuts et règlements](/statuts_reglements_aphcq_7_juin_2013.pdf).

Comme on sait, il s'agit d'un hyperlien format markdown.

**Note 2**: Éviter les accents, espaces, lettres majuscules dans les noms de fichiers. 

Au lieu de "Statuts et réglements APHCQ (7 juin 2013).pdf ", "statuts_reglements_aphcq_7_juin_2013.pdf" est mieux car ce sera compatible avec tous les fureteurs et systèmes. 

**Note 3**: Comment structurer les hyperliens:

Tu as mis "site-web/docs/Statuts et réglements APHCQ (7 juin 2013).pdf", or il faut mettre:

/statuts_reglements_aphcq_7_juin_2013.pdf

Pourquoi? Si on regarde où est placé ce fichier dans le **code source**, il est docs/statuts_reglements_aphcq_7_juin_2013.pdf

Donc on peut le visionner au https://github.com/aphcq-association/site-web/blob/master/docs/statuts_reglements_aphcq_7_juin_2013.pdf

**Tout ce qui est dans le répertoire docs correspond au site web, donc, il n'existe pas du point de vue du visiteur, un endroit /docs sur le site web": docs/xyz dans le code source correspond à /xyz sur le site web; ainsi l'hyperlien doit être formatté ainsi: /statuts_reglements_aphcq_7_juin_2013.pdf et est disponible en ligne au http://aphcq.dcycleproject.org/statuts_reglements_aphcq_7_juin_2013.pdf

Noter qu'il est aussi possible de formatter son hyperlien ainsi: 

    [Voir nos statuts et règlements](http://aphcq.dcycleproject.org/statuts_reglements_aphcq_7_juin_2013.pdf).

Par contre ceci est à déconseiller car ça va briser quand on changera de nom de domaine.

SVP m'indiquer si tu as des questions là-dessus!

**Comment by yanic1665** [comment]
Salut Albert,

Merci de toutes ces explicaitons et mises en garde. Et désolé de t'avoir
généré du travail. J'ai bien réalisé à un moment donné que je n'avais pas
fait la bonne affaire, mais je ne savais plus comment effacer mon erreur...
Notamment la formulationd des fichiers: j'ai fait le travail à moitié en ne
remfurlant que le titre du fichier, et mes les allusions ce fichier dans le
site..  On jour, je prendrai des cours!

Yanic

Le dim. 22 mars 2020, à 11 h 05, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
Par contre, quand je clique  sur le mot "ici" dans a plage http://aphcq.dcycleproject.org/apropos.html pour accéder aux statuts et
règlements dans la page, le pdf ne se télécharge pas et un message
d'erreur apparaît. Est-ce normal? j'ai vu que tu avais ajouté un lien en bas de la page, mais il faudrai dédoubler l'hyperlien pour l'associer au mot "ici" dans le texte.

Et tant qu'à y être, il faudrait insérer un lien dans l'adresse de courriel aphcq.histoire@gmail.com qui figuren dansla mpeme page, pour que çaouvre vers une app de courriel (comme avec l'adresse dans l'entête du site).
