### ISSUE TITLE
Numéro du Bulletin à ajouter dans l'ancien et le nouveau site

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#24]

**Comment by yanic1665** [comment]
Exceptionnellement, on a pris la décision de rendre public un numéro du bulletin même s'il est publié depuis d'un an. Focher pdf ci-joint:
[bulletin_special_aphcq_automne 2019.pdf](https://github.com/aphcq-association/site-web/files/4371829/bulletin_special_aphcq_automne.2019.pdf)

Il faudrait donc:

1. Ajouter au nouveau site lien vers ce nouvau numéro dans la page des bulletin. J'ai créé une ligne pour ce numéro, mais je n'a pas osé ajouté et lier le fichier pdf.

2. Il faudrait aussi l'ajouter dans la page du cline l'ancien site hébergé sur Github, pour qu'il soit accessible lorsqu'au j'aurai modifié défintivement les configurarions de redirection.  Cela a été fait sur la version actuelle du site accessible au public (http://aphcq.ca/scripts/aphcq.pl?browse&Bulletin) dans la dernière ligne de la page. Attention toutefois: il y a une erreur de numérotation (ce n,est pas le vl 25 no 2), il fauudrait donc dans notre cas ajouter une nouvelle ligne à la fin qui dit plutôt "Numéro spécial du Bulletin (automne 2019)"

**Comment by alberto56** [comment]
Salut @yanicviau 

J'ai ajouté le dernier bulletin dans http://aphcq.dcycleproject.org/bulletin.html

Je me suis aussi assuré que le dernier bulletin se trouve dans http://www.aphcq.ca/bulletin.htm

**Il ne faut pas oublier que www.aphcq.ca et aphcq.ca sont deux sites complètement différents**

**Comment by yanic1665** [comment]
Merci! Oui, je vais m'occuper des redirections
*à propos de  www.aphcq.ca <http://www.aphcq.ca> et aphcq.ca
<http://aphcq.ca> *

Le lun. 23 mars 2020, à 17 h 43, Albert Albala <notifications@github.com> a
écrit :
