### ISSUE TITLE
le "backend" (interface administrative pour gérer le contenu)

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#26]

**Comment by alberto56** [comment]
@yanic1665 pourrais-tu SVP aller au http://aphcq.dcycleproject.org/admin et cliquer sur "login with GitHub", et me dire si tu vois le panneau d'administration? Tu ne verras pas encore le contenu, c'est normal. Je veux seulement voir si tu peux te connecter.

**Comment by yanic1665** [comment]
Oui, je parviens à me connecter.

Yanic

Le lun. 30 mars 2020, à 13 h 27, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
Au fait, je t"ai autorié un accès à mon compte, comme on m ele proposait,
mais peut-être était-ce là une mesure excessive? Devrais-je éliminer cette
accès?

Yanic

**Comment by alberto56** [comment]
@yanic1665 pour l'instant c'est mon compte qui est là. À terme il faudra décider quel compte est le propriétaire du site et il faudra donner tous les accès à ce compte. Pour l'instant c'est mon compte mais on peut ou bien mettre le compte de quelqu'un chez APHCQ, ou encore faire un compte bidon qui n'appartient à personne qui a pour seule raison d'être d'être "propriétaire" du site. (Il faut que ce soit un compte d'utilisateur, pas un organisme). Dis-moi ce que tu préfères et on l'installera.

**Comment by yanic1665** [comment]
Tu peux rester propriétaire pour l'instant. Je soumettrai la quesiton en temps et lieu.

**Comment by yanic1665** [comment]
Je vais me cérer un billet pour ne pa soublier ça.

Yanic

Le lun. 30 mars 2020, à 15 h 11, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
J'ai mis à besoin d'approbation, et j'ai ouvert #41 et #42 pour faire suite.

@yanic1665 si tu te connectes maintenant tu verras quelque chose comme ça:

![Screen Shot 2020-03-30 at 3 43 28 PM](https://user-images.githubusercontent.com/808265/77955079-a1e82900-729d-11ea-842f-6a144977cb59.png)

Il faut confirmer que tu peux modifier les pages, les articles, les items de carousel, les boîtes oranges, les items de menu de Paypal, et les items de menu.

SVP documente tes questions ou commentaires ici.

**Comment by yanic1665** [comment]
@alberto56 , je peux modifier les sections suivantes dans l'interface administrative: Pages, Articles, Items de menu Paypal.

Problèmes rencontrés; 

* [x] 1. Le texte de La page "English" n'apparaît pas quand je sélectionne cette page. Tout les champs du formulaire y sont vides. 
* [x] 2. Texte de l'article "Nouveau site web": je ne comprends pas à quelle page ou section de page cet article correspond, puisqu'il réfère à deux photos qui se trouvent sur des pages différentes.
* [x] 3. Problèmes avec le Carrousel: quand je tente de modifier le titre ou le texte d'une des photos du carrousel,  on m'oblige à remplir le champs "Sous-titre" pour sauvegarder les modifications (alors que nous avions décider de ne pas en mettre).
* [x] 4. Problèmes similaire avec les boites oranges: quand le modifie uneligne de texte, on m'oblige à compléter les champs vides des autres lignes pour pouvoir sauvegarder les modifications.
* [x] 5. Je ne trouve aucune section qui me permette de mdofier les "itemsde menu". Je vois une section appelée "Section", mais lorsqu'on clique dessus, celle-ci est vide (et on dit "0 items") .

**Comment by alberto56** [comment]
> 1. Le texte de La page "English" n'apparaît pas quand je sélectionne cette page. Tout les champs du formulaire y sont vides.

OK c'est bon là.

> 2. Texte de l'article "Nouveau site web": je ne comprends pas à quelle page ou section de page cet article correspond, puisqu'il réfère à deux photos qui se trouvent sur des pages différentes.

C'était une fonctionalité que nous avons retiré; j'ai enlevé la section "articles", on pourra la remettre éventuellement. Puisque la page "congrès" était un article, j'en ai fait une page "normale".

> 3. Problèmes avec le Carrousel: quand je tente de modifier le titre ou le texte d'une des photos du carrousel, on m'oblige à remplir le champs "Sous-titre" pour sauvegarder les modifications (alors que nous avions décider de ne pas en mettre).

OK essaie là.

> 4. Problèmes similaire avec les boites oranges: quand le modifie uneligne de texte, on m'oblige à compléter les champs vides des autres lignes pour pouvoir sauvegarder les modifications.

OK, idem, peux-tu réessayer?

> 5. Je ne trouve aucune section qui me permette de mdofier les "itemsde menu". Je vois une section appelée "Section", mais lorsqu'on clique dessus, celle-ci est vide (et on dit "0 items") .

OK ça devrait marcher maintenant.

**Comment by yanic1665** [comment]
OK, tout est beau. À noter:, il faut faudrait écrire "carrousel" dans le
menu, et non carousel. Moi-même je me mélange tout le temps...

Le mar. 31 mars 2020, à 13 h 06, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
Nouvelle demande: serait-possible, dans l'interface adminsitrative / section "Carrousel", de rendre le champ "Texte" optionnel, comme tu l'as fait avec le champ "sous-titre"?. Peut-être qu'il es tun peu tard pour ça, mais je trouve que la taille du texte dans le champs "texte " est petite en comparaison avec le titre, alors j'aurais aimé expérimenté pour voir ce que aça donne quand on utlise plutôt le champ "sous-titre".

**Comment by alberto56** [comment]
OK pour Carrousel vs carousel! tu as raison. Je vais le changer car je suis perfectionniste. Pour le texte optionnel, ok, c'est pas compliqué, ça devrait être fait.

J'ai aussi mis le CMS en français.
