### ISSUE TITLE
Gestion des photos

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#28]

**Comment by yanic1665** [comment]
Voici des précisions sur les tâches à faire concernant la gestion des photos dans le site. 

Si la trop grande diversité de photos dans le site entraîne une cacophonie visuelle, et qu'il serait préférable de reprendre, dans chaque page, la photos de caroussel correspondante par souci de cohérence et d'haromievisuelle,  je n'ai pas d'objection à en réduire le nombre pour qu'on réutilise les mêmes 5 photos (quitte à faire quelques ajouts si ona rrive à faire rentrer deux photos par page).

* [x] Page d'accueil:  la première photo du carrousel  a été remplacée par Yanic par la photos suivante. https://drive.google.com/open?id=1gs0s0kfLk_JnQrZDuUFDDfXksnM2t1Np
Vérifier que le code est OK.Les autres photos ont été réordonnées par Yanic (d'où la numérotation désordonnée des fichiers dans les lignes de code). 

* [x]  Page "À propos de l'APHCQ" :  il faut ajouter dans le texte la photo de groupe de l'exécutif
https://drive.google.com/open?id=1eegdomtO43krbI2AHza8lvjcFSEr7qgI
ainsi que la photo potrait de la personne manquante (Catherine) jsute à côté 
(https://drive.google.com/open?id=1DqI5NhgM22LEPp-Q3ZyPDFBEPFWCqCUN), juste au-dessus du texte qui débute par le mot "Légende" (l'endroit a été indiqué dans la page).

* [x] Page "À propos de l'APHCQ": remplacer la photo de la colonne de droite par une plus belle photo, à savoir: https://drive.google.com/drive/folders/1w6AOzXUbMeIj2dziyxp5yUycVKVjJhs5

* [x] Page "À propos de l'APHCQ": l'adresse de courriel aphcq.histoire@gmail.com insérée dans le texte devrait être en hyperlien.

* [x] Page "À propos de L'APHCQ":  la photo de droite devrait être remplacée par celle-ici (la même que dans la carrousel): https://drive.google.com/open?id=1GQxqjHqsptKgB3Es9jTQkueT5jE-UjuE

* [x] Page "Congrès": Il faudrait ajouter les deux photos suivantes dans la colonne de droite, en remplacement de la photo actuelle: 
https://drive.google.com/open?id=1eDLjrEfcUHUZ4fib_ahJg9eVUCP_pUmS
https://drive.google.com/open?id=1TULxDlVjMePWDNfvXDkfomAM6dcMQ3zu
Et il faudrait changer la photo de bannière actuelle par celle-ci (à recadrer au besoin); 
https://drive.google.com/open?id=1cY4oK9XH44uK4aDEsYBoqPikASrD5unS

* [x] Page "Devenir membre": remplacer la photo de droite par la photo suivante:
https://drive.google.com/open?id=1pWLNKsOg4doun2Aqu2onK-uPaG1xIwWT
et recadrer la photo de bannière afin de conserver la bande horizontale centrale (avec plus de monde), et non la bande du haut . 

* [x] Page "Bulletin" insérer  deux images de  la couverture du Bulletin (et pourquoi pas trois) dans la colonne de droite. Voir les  fichiers pdf dans ce dossier: https://drive.google.com/drive/folders/1cynxYHdj2AYfeIVpGp7aglGhWw28MkmW. S"assurer ensuite dans la versiom mobile que le ggrnd alinéa (espace blanc) qui se trouve entre le titreen oir et et le dénut du texte soit élminé (ce qui est le cas dans les autres pages où il y a déjà des photos (voir le problème dans la caputre d'écran ci-jointe).

![Capture d’écran, le 2020-04-01 à 14 27 54](https://user-images.githubusercontent.com/61343142/78184084-ece97400-7436-11ea-9545-81ff93f90fff.png)



* [ ] Page "About APHCQ": Insérer la photos suivante dans la page de droite (à recadrer au besoin), et enutliser une versionr recadrée pour la bannière de la page:
https://drive.google.com/open?id=1eRJH70aezgaGz5EQgGIE3TcxDuCP7J_S

**Comment by yanic1665** [comment]
@alberto56 , la liste de tâches vient d'être modifiée afin de tenir conpte des derniers travaux réalisés et de préciser les photos qui sont requises dans chaque cas.

**Comment by yanic1665** [comment]
@alberto56   Ajout  d'une nouvelle tâche dans la liste (format de la première photo du carrousel à comprimer pour en accélérer le téléchargement lors de la visite du site).

**Comment by alberto56** [comment]
Il est dorénavant possible de spécifier dans le CMS comment décaler les bannières. Dans cet exemple (page Adhérez), on une règle qui décale la bannière du haut de 95 pixels vers le haut mais seulement si la page fait plus de 875 pixels. (Ainsi la bannière ne sera coupera pas la tête de la prof sur mobile). Voir capture d'écran:

<img width="841" alt="Screen Shot 2020-04-08 at 8 55 53 AM" src="https://user-images.githubusercontent.com/808265/78786569-f6af3200-7976-11ea-91a9-a6ea31e08993.png">

**Comment by alberto56** [comment]
Tout devrait être OK, toutefois je crois qu'il y a eu un bogue dans la capture d'écran pour la section "bulletins". @yanic1665 pourrais-tu SVP fermer le présent billet et ouvrir de nouveaux billets la [page bulletin](http://aphcq.dcycleproject.org/bulletin.html) et toutes les autres tâches restantes au besoin?
