### ISSUE TITLE
Redirection du nom de domaine aphcq.ca. du site hébergé par Aztus vers le clone du site sur Github

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#3]
Suivi: une demande d'information a été envoyée par Yanic à Aztus à ce sujet (25
 fév.), 
Contexte: le client est responsable de rediriger son domaine « aphcq.ca » vers l'hébergement GitHub pages en utilisant la fonctionnalité CNAME (consulter votre registraire actuel de site à propos de la procédure à suivre).

**Comment by alberto56** [comment]
L'entrée CNAME doit être "aphcq-association.github.io." (ne pas oublier le point à la fin).

![Screen Shot 2020-02-25 at 3 20 07 PM](https://user-images.githubusercontent.com/808265/75284208-521bcb00-57e2-11ea-84e7-0e293dbef80b.png)

**Comment by alberto56** [comment]
De @yanicviau 

> [ Une erreur s'est produite ] Impossible de modifier les pointeurs pour ce domaine. Le domaine aphcq.ca est hébergé" . Je viens d'ouvrir un billet auprès de Aztus à ce sujet et j'attends la réponse., 

voir aussi le billet Aztus ticket:GQP-663657

> 
> Donc, ce qui serait la meilleure option serait de modifier les NS pour qu'ils pointent déjà vers votre nouvel hébergeur. Comme ceci, lorsque vous transférerez le domaine de registraire, il n'y aura pas de "downtime" car les NS ne changeront pas.
> 
> Il faudrait vérifier avec votre nouvel hébergeur qu'il s'assure que la zone DNS est prête de son côté et qu'il vous transmette les NS à appliquer au domaine.
> 
> Vous pouvez confirmer avec votre nouvel hébergeur pour ceci. 

Ceci veut dire qu'actuellement on a quelque chose comme ceci:

    |--------------------------AZTUS-----------------------------|
    |                                                            |
    |     APHCQ.CA---------(hégergé)----------->VIEUX SITE       |
    |                                                            |
    |------------------------------------------------------------|

    |--------------------------GITHUB----------------------------|
    |                                                            |
    |     CLONE DU VIEUX SITE                NOUVEAU SITE        |
    |                                                            |
    |------------------------------------------------------------|


Ce qu'on veut c'est 


    |--------------------------AZTUS-----------------------------|
    |                                                            |
    |     APHCQ.CA----(CNAME(*))---|            VIEUX SITE       |
    |                              |                             |
    |------------------------------+-----------------------------|
                                   |
    |--------------------------GITHUB----------------------------|
    |                                                            |
    |     CLONE DU VIEUX SITE                NOUVEAU SITE        |
    |                                                            |
    |------------------------------------------------------------|

    (*) "aphcq-association.github.io."
    (*) ne pas oublier le point à la fin.
    (*) pas de guillemets

Github va savoir que APHCQ.CA doit présenter le clone du vieux site car, dans le code du clone, nous avons un document qui s'appelle ["CNAME"](https://github.com/aphcq-association/aphcq-avant-2020/blob/master/CNAME) qui contient "aphcq.ca". Une fois que nous allons être prêt à changer pour le nouveau site, nous allons retirer ce document du clone et ajouter un CNAME avec "aphcq.ca" dans le nouveau site.

Ainsi, il faut dire à AZTUS que, oui, le site est actuellement hébergé chez eux mais que tu veux tout de même changer le CNAME mais que leur tableau de bord ne te permet pas de le faire.

**Comment by yanic1665** [comment]
J'ai réussi à parler à un représentant de l'hébergeur actuel du site Aztus qui m'a expliqué la procédure pour rediriger le nom de domaine aphcq.ca vers aphcq-association.githun.io.  Il m'a dit que ça prendrait une adresse IP et la seule àma disposition est aphcq-association.githun.io.

Aussi, dans les 13 options disponibles dans la pages de configurations DNS, lorsque je clique sur l'option "CNAME"', je ne vois pas de possibilité d'ajouter l'adresse ci-haut (se temrminant pa  .io), puisque par défaut, l'adresse à saisir ne peut que se terminer par aphcq.ca. Peut-être suis-je au mauvaus endroit. J'ai fait des captures d'écran (ci-jointes).

Veux-tu avoir accès à la page de configurations DNS? Ce serait peut-être plus simple. pur cel,i fat d'abord se conencter à https://pkwu1.interface-web.com:8443/login_up.php (me contacte pour les coordonnées).  Tu peux faire les changements, mais dans tous les cas, j'aimerais bien que tu me dises après comment tu les a fait.

![Capture d’écran, le 2020-03-12 à 10 16 33](https://user-images.githubusercontent.com/61343142/76531795-1a508c80-644c-11ea-93b4-793f93829fba.png)
![Capture d’écran, le 2020-03-12 à 10 17 12](https://user-images.githubusercontent.com/61343142/76531801-1cb2e680-644c-11ea-975f-d0fc901fbd48.png)

**Comment by alberto56** [comment]
OK, essaie de mettre "aphcq-association.github.io" dans ce champ (entouré en rouge): sans point toutefois, voir ma note ci-dessous.

**important: il y a déjà un point (.) à la fin
du champ, donc mettre dans le champ: aphcq-association.github.io (sans point final)"

![Screen Shot 2020-03-12 at 11 05 28 AM](https://user-images.githubusercontent.com/808265/76535518-6520d300-6451-11ea-81b1-8b1c29446573.png)


à titre d'information, l'IP actuelle du site est 72.10.147.9; lorsque l'IP sera 185.199.110.153, on saura que le transfert sera fait correctement; en principe le site devrait demeurer accessible, mais laisse-moi savoir si tu as des problèmes d'accès.

**Comment by yanic1665** [comment]
C'est fait! Voici la capture d'écran du menu DNS qui en résulte.  Peux-tu savori si ça a fonctionné?  Il y a peut-être un délais pour enregistrer le changement?

![Capture d’écran, le 2020-03-12 à 11 25 05](https://user-images.githubusercontent.com/61343142/76537651-78816d80-6454-11ea-9325-17714b6808c9.png)

**Comment by alberto56** [comment]
@yanicviau 

Il y a une erreur dans le nom, c'est "github" et non "githun" qu'il faut mettre.

<img width="575" alt="Screen Shot 2020-03-13 at 8 34 59 AM" src="https://user-images.githubusercontent.com/808265/76621364-98249e80-6505-11ea-8d66-179a5da703fd.png">

Prochaines étapes:

* faire ce changement
* attendre que www.aphcq.ca fonctionne
* retourner dans Aztus et faire une redirection de "aphcq.ca" vers "www.aphcq.ca"

**Comment by yanic1665** [comment]
La correction vient d'être apprortée dans l'interface de gestion du nom de
domaine de l'hbergeur Aztus (vendredi 11h35). Désolé de cette erreur! Yanic

Le ven. 13 mars 2020, à 08 h 36, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Excellent, ça marche!

* http://aphcq.ca/ c'est votre site sur Aztus
* http://www.aphcq.ca/ c'est le clone de votre site sur GitHub

Pourrais-tu maintenant effacer les entrées NS pour aphcq.ca et ajouter une "redirection" de 
aphcq.ca vers "http://www.aphcq.ca?

<img width="702" alt="Screen Shot 2020-03-13 at 3 16 16 PM" src="https://user-images.githubusercontent.com/808265/76652778-aa223380-653d-11ea-97c9-c8f03365e902.png">

Une fois que ce sera fait, le fait de taper http://aphcq.ca/ redirigera automatiquement vers http://www.aphcq.ca/

**Comment by yanic1665** [comment]
Mon collègue Chrisrian a réussi a mettre à jour la page d'accueil l'ancien site afin d'informer les membres de l'annulation du congrès, et cette mise è jour est bien visible en ligne. Est-ce à dire que la redirection du nom de domaine vers le clone du site sur Github n'a pas fonctionné?

**Comment by alberto56** [comment]
* http://www.aphcq.ca est le clone de l'ancien site
* http://aphcq.ca est l'ancien site (sans www.) et contient l'alerte pour le Coronavirus.

Les prochaines étapes sont:

* [x] Mise à jour de www.aphcq.ca
* [ ] Redirction de la version non-www à la version www (ceci se fait sur Aztus)

**Comment by alberto56** [comment]
Je viens de mettre à jour http://www.aphcq.ca pour qu'il ait le même contenu que http://aphcq.ca, reste à faire la redirection.

**Comment by yanic1665** [comment]
Je viens de faire les changements demandés dans les configuration DNS dans Plesk (hébergeur Axtus).  @alberto56 peux-tu me dire si cela a fonctionné? Concrètement, j'ai éliminé les deux enregistrements NS menant à pk1.aztus.com.  et pk2.aztus.com., et j'ai créé un nouvel enregistrement NS menant de "aphcq.ca" (à l'instar des deux enregistrements éliminés, j'ai laissé le champs précédent libre pour éviter qu'il y ait un "www") , vers  aphcq-association.github.io.
![Capture d’écran, le 2020-03-23 à 22 15 34](https://user-images.githubusercontent.com/61343142/77381335-f9ddd780-6d53-11ea-9ba0-5a81cd8b657b.png)

**Comment by alberto56** [comment]
Non c'est pas les bonnes valeurs, essaie ce qui est dans l'image ci-jointe.

Type: redirection
Valeur: http://www.aphcq.ca

Si "redirection" n'existe pas dans la liste des types possibles, SVP inclure une capture d'écran des valeurs possibles.

<img width="858" alt="Screen Shot 2020-03-23 at 10 53 04 PM" src="https://user-images.githubusercontent.com/808265/77383370-1fb9ab00-6d59-11ea-8124-48c94d6542f7.png">

**Comment by yanic1665** [comment]
Mais quel acronyme dans la liste suivante correspond à une redirection? Aucun des formulaires correspondant à ces options ne semble exiger les infos que tu me demandes d'ajouter (on demandes  un adresse IP.  etc.). 

A
AAA
CNAME
MX
PTR
TXT
SRV
DS
CAA

À moins que je ne doice à accéder à une autre option dans le menu offert par Plesk? Par exemple: 

![Capture d’écran, le 2020-03-23 à 23 22 38](https://user-images.githubusercontent.com/61343142/77385014-4ed21b80-6d5d-11ea-8db5-c8d5cc700c95.png)

![Capture d’écran, le 2020-03-23 à 23 22 50](https://user-images.githubusercontent.com/61343142/77385016-50034880-6d5d-11ea-9141-17cfa32f31a2.png)

**Comment by alberto56** [comment]
Hmmm ça ne semble pas exister, tu peux faire un CNAME pour "aphcq-association.github.io." et je ferai la redirection directly sur github.

**Comment by yanic1665** [comment]
J'ai tenté ta solution, mais ça disait que c'était impossible à faire parce que ça entrait en conflit avec le "glue record" (???). Pour repartir à neuf, j'ai donc éliminé l'enregistement NS que j'avais créé hier mais qui ne servait pas, et j'ai recréé les deux enregsitrements NS qui s'y trouvaent originalement (ceux menant à menant à pk1.aztus.com. et pk2.aztus.com). J'ai ensuite créé un nouvel enregistrement CNAME menant de "aphcq.ca" vers "aphcq-association.github.io."  mais le   même message d'erreur apparaît: "Erreur: Cet enregistrement sera en conflit avec le glue record pour la zone 'aphcq.ca'."  Puis-je te demander de consulter et modifer directement le tableau de bord Plesk sur le site Aztus? (par Signal). Ce serait plus simple.

**Comment by alberto56** [comment]
Si tu utilises Plesk comme système de gestion, [ces instructions](https://websavers.ca/setup-301-redirect-plesk-use) pourraient marcher.

Si tu préfères que j'essaie, envoie-moi par Signal les infos pertinentes pour se connecter à Aztus.

**Comment by yanic1665** [comment]
C'est fait!  Voir sur Signal.



Le mar. 24 mars 2020, à 11 h 50, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Je m suis connecté et c'est en anglais pour moi, pas sûr pourquoi. Bref, j'ai coché une case qui dit que je préfère que le site web s'affiche comme "www.aphcq.ca" et non "aphcq.ca" ou "sans préférence".

J'ai eu un message comme qui ce serait actif dans 30 minutes. 

Je pense que ce que ça veut dire c'est que dès que Aztus reçoit une requéte pour aphcq.ca, il va faire une redirection immédiate vers www.aphcq.ca, qui est la version hébergée sur github (clone).

Voici image ci-jointe.


![Screen Shot 2020-03-24 at 1 00 41 PM](https://user-images.githubusercontent.com/808265/77455118-d5bfdc00-6dcf-11ea-8d50-1e22d12bf62b.png)

**Comment by alberto56** [comment]
OK ça semble avoir marché, pour tester, ouvrir un fureteur et taper:

http://aphcq.ca

ça devrait rediriger vers

http://www.aphcq.ca

Si ça ne marche pas, simplement rafraîchir quelques fois.

@yanic1665 il est maintenant OK pour toi de désactiver le renouvellement automatique de l'hébergement chez Aztus, laissant seulement le nom de domaine. Je te laisse le soin de fermer ce billet quand ce sera fait.

**Comment by yanic1665** [comment]
Merci, ça marche effectivement.

Je m'occupe des changements au contrat avec Aztus, mais je vais faire ça
plud tard, question de priorités. Je l'ai mis dans la liste de tâches en
guise d'aide-mémoire pour moi-même.

On se parle à 17h

Yanic

Le mar. 24 mars 2020, à 13 h 11, Albert Albala <notifications@github.com> a
écrit :
