### ISSUE TITLE
Faciliter la redirection des nouveaux membres vers le site après un paiement par Paypal

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#30]

**Comment by alberto56** [comment]
Je viens de faire un achat de 1$ et il y a maintenant un bouton qui dit retour chez le marchand.

<img width="457" alt="Screen Shot 2020-04-08 at 9 06 44 AM" src="https://user-images.githubusercontent.com/808265/78787470-67a31980-7978-11ea-8d53-74a7fd2d6962.png">


Qui redirige vers la page http://aphcq.dcycleproject.org/merci-pour-votre-achat.html

@yanic1665 tu peux changer le texte au http://aphcq.dcycleproject.org/admin/#/collections/pages/entries/merci-pour-votre-achat

J'ai tenté un autre achat que j'ai annulé en cliquant sur "cancel and return to merchant" (c'est en anglais, je crois, car #44 n'est pas fermé).

ça me ramène à http://aphcq.dcycleproject.org/achat-annule.html

Tu peux modifier ça au http://aphcq.dcycleproject.org/admin/#/collections/pages/entries/achat-annule

**Comment by yanic1665** [comment]
@alberto56  Merci!
