### ISSUE TITLE
Problèmes avec l'édition du contenu de la page "Adhérer"

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#31]

**Comment by yanic1665** [comment]
Yanic a ajouté le texte attendu dans la page "Devenir membres" (http://aphcq.dcycleproject.org/adherez.html) mais plusieurs problèmes de mise en page sont apparus:

Dans la page https://github.com/aphcq-association/site-web/edit/master/docs/adherez.html: 

0. Le titre de la page a été changé piur "Devenir membre"  (ligne 6) maiscela ne se matérialise pas dans la page. 

1. Les alinéas créés dans les lignes de code  33 à 53 ne se matérialisent pas dans la page web. au lieu de cela, la mise en forme demeure celle de la page de codage

2. En plusieurs endroits, les sous-titre ont été modifiés sans que ça be fonctionne (ligne 11) et en plusieurs endroits,  les doubles astérisques ne convertissent le texte en gras comme voulu.

3. Je souhaiterais faire remonter le bouton Paypal plus haut dans la page (là où je t'ai laissé une note, à la ligne 45), mais je ne  vois pas le menu déroulant dans les lignes de code et quand je le retouve ailleurs dans linterface, je ne sais pas comment le déplacer .

4. Une conséquence du problème mentioné au point 3, c'est que l'incorporation du formulaire Google dans la page ne fonctionne pas. Pourtant, lors de mes premiers essais, cela avaat très bien fonctionné.

5. J'ai modifié les montants dans les options de paiement Paypal, mais les sommes saisies ont été mal lues et mal rendues: 25,00$ est devenu 25 000$; 50,00$ est devenu 50 000$; et 0,50$ (50 cents) devient... 40,00$!

**Comment by alberto56** [comment]
Pourrais-tu vérifier maintenant? 

[J'ai fait ces changements](https://github.com/aphcq-association/site-web/commit/bfb09e8caa180f972ce5949a6563ecef04dab7d2) que je t'invite à regarder:

* Pour les sous-titres de sections, j'ai utilisé `## xyz` plutôt que `**xyz**`, les deux dièses dénotent une sous-section, et les astérisques dénotent du gras. Il est important de mettre une sous-section plutôt que du gras car ça donne aux personnes non-voyantes une indication sur la structure du document. Voir https://markdown-it.github.io

* En markdown, il ne faut jamais mettre des **espaces** avant une ligne, car le système va interpréter ça et le formatter comme code informatique. J'ai donc enlevé les espaces au début des lignes, c'est pour ça notamment que le iframe paraissait comme code et non comme formulaire.

* "Note à Albert mettre le paypal ici" je t'invite à ouvrir un nouveau billet pour ça.

* les autres points semblent réglés, sinon je t'invite à ouvrir de nouveaux billets.
