### ISSUE TITLE
Problèmes lors de la modification du contenu de la page d'accueil

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#32]

**Comment by yanic1665** [comment]
J'ai tenté de modifier certains éléments de la page d'accueil. Le nouveau contenu est visible dans les lignes de code (https://github.com/aphcq-association/site-web/blob/master/docs/_config.yml), mais cela ne se matérialise pas dans la page web. Notamment:

*  [x] 1. J'ai vous modifié (en vain) les titres et le texte qui accompagnent les cinq photos dans le carrousel , j'ai ajouté des actions correspondantes dans certains cas, et j'ai modifié l'ordre entre deux photos (ligne 27 à 58), mais rien ne se concrétise. Rappelon que le nouvel ordre de sphots doit être le suivant (je fais ici allusion sujet des pages, pas au libellédes titres que je souhaite voir, lesquels sont dans les lignes de code): 
    - Qui sommes-nous?
    - Congrès annuel
    - Bulletin de l'APHCQ
    - Adhérez
    - Sur Facebook

* [ ] 2. J'ai voulu mettre le mot "Avis" en gras dans la première boite orange (Congrès 2020), mais en vain.

* [x] 3. Il faudrait inverser les deux icônes qui se trouvent dans les deux premièes boîtes oranges, si possible: le coeur avec le symbole $  devrait aller dans la boîte "Devenez membres", et les deux maibs qui se serrent la main devraient aller dans la boite "Congrès 2020".

**Comment by alberto56** [comment]
Rapidement comme ça, je suis allé sur https://github.com/aphcq-association/site-web/commits/master et j'ai identifié la première modif qui ne passe pas (x rouge, voir image ci-jointe):

<img width="826" alt="Screen Shot 2020-03-25 at 12 42 58 PM" src="https://user-images.githubusercontent.com/808265/77562248-2ac62580-6e96-11ea-9d01-3950d1c8f0e8.png">

J'ai identifié deux problèmes:

(1) Un point doit obligatoirement être utilisé pour les points décimaux en PayPal. On peut quand même afficher une virgule plutôt qu'un point -- svp ouvrir une tâche pour ça, mais laisser un point pour la représentation interne du prix

(2) en langage YAML, si une valeur d'un champ contient un deux-points, il faut mettre toute la valeur en guillemets. En fait c'est une bonne pratique de toujours utiliser des guillemets. Ainsi:

    nom: Catégorie 1: 

va causer une erreur, mais:

    nom: "Catégorie 1: " 

est OK

**Comment by alberto56** [comment]
Ça semble OK maintenant, SVP confirmer

<img width="859" alt="Screen Shot 2020-03-25 at 12 51 34 PM" src="https://user-images.githubusercontent.com/808265/77563250-67465100-6e97-11ea-8f3f-a31c8d55f486.png">

**Comment by yanic1665** [comment]
C"est bon, ça semble marcher!

Le mer. 25 mars 2020, à 12 h 52, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
@alberto56 Je ferme ce billets, car toutes les tâche dans  la liste ont été complétées ou transférées ailleurs en #18
