### ISSUE TITLE
Déplacement du menu Paypal plus haut dans la page "Adhésion".

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#33]
Le menu déroulant qui se toruve actuellement au bas de la page est à déplacer ici. Il faudrait aussi 
insérer une alinéa pour le déplacer légèrement vers les droite. 

https://github.com/aphcq-association/site-web/blob/78fcc5d604288a723f091a8304b932bddeb7f71b/docs/adherez.html#L44

**Comment by alberto56** [comment]
Devrait être bon maintenant.

**Comment by yanic1665** [comment]
Oui, merc!
