### ISSUE TITLE
Texte des lignes 48-52 (adresse et note bene) à déclarer vers la droite

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#34]
Les lignes 48 à 52 devraient être décalées légèrement vers la droite (alinéa à insérer).

https://github.com/aphcq-association/site-web/blob/6ec6d8c4cecb1fa4ab9e5d85088ec5b2e76ed9d2/docs/adherez.html#L48

**Comment by alberto56** [comment]
Devrait être bon.

**Comment by yanic1665** [comment]
Oui, merci!
