### ISSUE TITLE
Liste des modifications à apporter au site

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#35]
Listes des commentaires des membres du comité exécutif portant sur des enjeux que Yanic ne peu résoudre.
N.B. Liste en construction, jusqu'à l'échéance du 3 avril 2020.

Page d’accueil et menus du site

* [x] Dans la boîte organge du Congrès:, le  mot "Avis"  devrait être en gras.

* [x] Dans le menu du bas, le titre de colonne « Liens utiles » devrait être remplacé par le libellé « Plan du  site », pour éviter la confusion (un utilisateur essayait en cliquer sur « liens utiles » pour accéder à une liste de liens..)

* [x] Dans le menu du bas, le lien « Accueil" ne fonctionne pas

* [x] Dans le menu du bas, ajouter un lien menant au  « Congrès annuel ».

Autres pages du site:

* [x] Page « À propos », section Pour en savoir plus : ce serait bon que le lien « Coalition pour l’histoire » ouvre un autre onglet afin de ne pas fermer la page de APHCQ

* [x] Page « Bulletin » Le lien vers le « Dépôt des publications numériques » devrait aussi s’ouvrir dans une nouvelle page afin de ne pas quitter le site de l’APHCQ

* [x] Page "Congrès", il y maintenant un paragraphe renvoyant à  la page "Adhérer" pour payer les frais d'inscription au Congrès . ll faudrait donc enlever le menu Paypal et les termes "Choisissez une option" qui viennent avec. 

* [x] Page "English": En attente de Catherine: révision de la page en anglais; Préférence entre  "About APHCQ' dans le titre, et "About the APHCQ" en surtitre (à chosir et uniformiser) :http://aphcq.dcycleproject.org/english.htm

Autres (enjeu impossible à résoudre)

* [x] Page "Adhérez": Dans le formulaire d’adhésion Google,  Paul constate il y a des termes en anglais .  Est-ce que Google Forms ne permet pas de les mettre en français? Réponse : le terme « email » ne peut être modifié (il est généré automatiquement lorsqu’on souhaite que le utilisateurs recoivent une copie du formulaire complété) .

**Comment by yanic1665** [comment]
Révision du site (tcontenu textuel et aspects formels) autre que le sphotos) encours depuis le 29 mars et ce, jusqu'à l'échéance du vendredi, 3 avril à 17h00.

**Comment by yanic1665** [comment]
@alberto56, prendre que tous les textes requis ont été intégérés au site. Ces textes sont co,plet, mêmes s'ils peuvent encore faire l'objet de retouches à la marge.

**Comment by yanic1665** [comment]
@alberto56 , j'ai commencé à ajouter dans la fenêtre de descrtiption de l'enjeu #35 les commentaires sur le site que les collègues m'envoient  (bien que je ne lees aie pas encore analysés). Je les ajouterais ferai au fur et mesure d'ici l'échéance fixée au 3 avril , mais comme certains d'entre eux concernent des aspects techniques (fonctionnemement et mise ne page de la version mobile), peut-être voudras-tu en prendre connaissance dès maintenant.

**Comment by alberto56** [comment]
@yanic1665 ok, je te laisserai analyser et corriger ce que tu peux; pour ce que tu ne peux pas corriger, SVP ouvrir des billets séparés, merci!

**Comment by yanic1665** [comment]
Ça me convient, merci!

**Comment by yanic1665** [comment]
@alberto56 La liste des changement. faire viebt d'être modifiée et augmentée. Désormais, elle ne contient plus que les commentaires des membres du comité exécutif qui portent enjeux que Yanic ne peut résoudre. Rappel: La liste sera fermée le 3 avril prochain.

**Comment by yanic1665** [comment]
@alberto56  Ça me semble complet. Je ferme le billet.
