### ISSUE TITLE
Carrousel photos: deux titres sont coupés en mobile

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#36]
Carrousel photos: deux titres sont coupés dans l’app mobile car ils occupent trois lignes au lieu de deux: “Notre congrès annuel", "Suivez-nous sur Facebook". Par ailleurs, dès qu'un titre occupent plus d'une ligne, ce qui est le cas de 4 titres sur 5, la case "Action" en organfe qui se trouve en dessous est également amputée et donc difficilement lisibles dans la version mobile.

(De #18)

**Comment by yanic1665** [comment]
C,est bon. Je ferme le billet.
