### ISSUE TITLE
version mobile : pas de flèches dans le carousel

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#37]
De #18

. Dans la version mobile, i n'y a pas de flèches qui permettent aux internautes de voir que les phtoos du carrousel peuvent être changé

**Comment by alberto56** [comment]
Ceci est voulu car en version mobile les flèches seraient trop petites pour cliquer et on peut défiler horizontalement avec les doigts.

En principe le carousel n'est pas conçu pour contenir des informations cruciales (non-disponibles par d'autres moyens), donc on appelle ça une "amélioration progressive" (progressive enhancement), c'est-à-dire que plus d'options sont disponibles sur la version complète que sur le mobile. On pourrait mettre des flèches mais ça ferait un visuel trop occupé à mon avis sans ajouter une foncitonalité importante.

**Comment by yanic1665** [comment]
Ok, je comprends. Je ferme le billet.
