### ISSUE TITLE
De #18: mobile: l'icône du menu en haut droite est presque invisible

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#38]
Dans la verison mobile,l'icône du menu en haut droite est presque invisible, étant "noyée" dans le nom de l'APHCQ qui se trouve dans l'entête

**Comment by alberto56** [comment]
@yanic1665 est-ce que tu veux dire ce menu ou un autre? Est-ce que c'est ça que tu vois?
![Screen Shot 2020-03-30 at 1 24 55 PM](https://user-images.githubusercontent.com/808265/77942646-e8338d00-7289-11ea-816b-8604c767d41b.png)

**Comment by yanic1665** [comment]
Oui, c,est exactement ça!

Le lun. 30 mars 2020, à 13 h 25, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Est-ce que quelque chose comme ceci serait OK?

![Screen Shot 2020-03-30 at 4 12 54 PM](https://user-images.githubusercontent.com/808265/77957357-5d5e8c80-72a1-11ea-87d6-fd4230339bb2.png)

**Comment by yanic1665** [comment]
Oui, mais reste à voir si le texte ne sera pas trop petit au final.

Yanic

Le lun. 30 mars 2020, à 16 h 13, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Quel texte?

**Comment by yanic1665** [comment]
Le nom de l'association et le logo sur un écran standard de cellulaire.

**Comment by yanic1665** [comment]
@alberto56 Je ferme ce billet.
