### ISSUE TITLE
Indiquer dans le site les conditions d'utilisation du contenu du site

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#39]
De #18

Indiquer dans le site les conditions d'utilisation du contenu du site (idéalement, avec droits restreint restreints pour les photos (sur demande uniquement), car elles appartiennent à des tiers.

**Comment by alberto56** [comment]
Est-ce qu'on a un texte pour ça? Ou je mets un "lorem ipsum" pour le moment?

**Comment by alberto56** [comment]
Voir dans le bas de page:

<img width="1046" alt="Screen Shot 2020-04-07 at 8 21 01 PM" src="https://user-images.githubusercontent.com/808265/78731298-5d980100-790d-11ea-82c9-447bb10933fb.png">

Traditionnellement la page LICENSE s'écrit à l'anglaise (plutôt que LICENCE) mais on peut le changer au besoin; la page se trouve avec le code au https://github.com/aphcq-association/site-web/blob/master/LICENSE, et non sur le site web lui-même, aussi c'est l'endroit traditionnel où le mettre. Donc ce n'est pas modifiable avec le CMS, il faut le modifier directement sur GitHub. Aussi, la coutume veut que la page LICENSE soit en texte brut et non en markdown.

**Comment by yanic1665** [comment]
@alberto56  Ça me va. Je comprends ton points, mais je me suis quand même permis de rétablir le "C" dans les deux occurences du mot "License". 

Voir: http://www.granddictionnaire.com/ficheOqlf.aspx?Id_Fiche=8872100

**Comment by yanic1665** [comment]
@alberto56  J'ai ajouté une mention dans le guide d'admnistraitn du site 
à ce sujet. Je ferme le billet.

**Comment by alberto56** [comment]
Merci, c'était des fautes de frappe de ma part! C'est plutôt le nom du fichier qui doit être à l'anglaise. Dans le texte, bien sûr, ça doit être en français!
