### ISSUE TITLE
Banque de photos à insérer dans le site

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#4]
Les photos autorisée mais non retouchées dans un dossier Google Drive distinct:  https://drive.google.com/drive/folders/1EAdQeAeEGnzgXeAeJx9VLQeyttIfFyNb

Un collègue, Sylvain Guilamin, les retouchera 5 photos suppélmentaires d'ici le 24 mars.  En attendant tout les versions dans le dossier sont réputées provisoires. Une de ces photos devra remplacer la première photo du carrousel de la page d'accueil (et ses formats dérivés un peu partout dans le site), à la suite de commentaires reçus . Hattends ces les nouvelles photos rertouchées d'ici mardi prochain (24 mars) à midi, avant notre réunion téléphonique.

Voici quelques précisions sur les photos  venir à données au collaborateur (SYlvain):
   - Exécutif APHCQ: format bannière (c'est déjà mal mal comme ça)
   - Atelier congrès St-Jérome: grande taille
   - Hôtel de ville: grande taille idéalemetnt (sinon,  petit taille c'est
   OK)
   - Public d'atelier: grande taille idéalemetnt (sinon, petit taille c'est
   OK)
   - Réunion d'nfo St-Jérôme: grande taille
   - Conférencier: grande taille

**Comment by alberto56** [comment]
@yanicviau 

> Un collègue, Sylvain Guilamin, les retocuhera et fer aune séelctio des meilleurs photos (d'après leur résolution, etc.) d'ici le 2 mars

Est-ce que c'est fait? Est-ce que je peux utiliser des photos en prévision de notre meeting de demain?

**Comment by yanic1665** [comment]
Oui, toutes les photos qui se trouvent dans le dossier sont des photos autorisées et retouchées. Les photos en traitement ont été retirées pour éviter la confusion. 

Ànoter: es photos sont numérotées en ordre de préférence pour un éventuel caroussel (défilement). Il manque encorel a photo no 1, qui sera disponible lundi, le 16 mars (image très importante, soi une scène de prof en train d'enseigner en classe, que notre président Paul Dauphinais prendra en photo en classe d'ici vendredi 13 mars, et que Sylvian Guilmain retouchera pour lundi 18).

**Comment by yanic1665** [comment]
Les photos pour la page d'accueil se trouvent à:
https://drive.google.com/drive/u/0/folders/100f93OrIJk5noeA6EGFdGlj_QQcOpY2k?hl=fr

Le sautres images possibles pur le site se trouvent à: https://drive.google.com/drive/u/0/folders/199_i8ddCc8O_lZP6jBTz98VvPwS34UYa?hl=fr

**Comment by yanic1665** [comment]
La première photo du carrousel de la page d'acceuil est touours en attente. Le photographe n'a pas livré la photo pour aujurd'hui tel que prévu. Je bien d'organise run p,an B. mais la photo ne sera disponible que lundi soir (16 mars) et la verisonfianle retouchée, uniquement le 17 ou 18 mars. Quelles sont les dimensions idéales à prévoir pour ces photos?

**Comment by yanic1665** [comment]
Finalement, le gouvernement vient d"annoncer la femrture des cgeps pur deux semaines. Il faut donc mettre une croix sur la possbilité de prendre des photos en classe. Nous devront faire avec les photos actuellement en notre possession. Je ferme donc le billet. .

**Comment by yanic1665** [comment]
À la demande de l,exécutif, nous allons finalement devoir remplacer certaines photos dans le caroussel de la page d'accueil (au moins une, la première à défiler: certaisn trouvent quil faudrait un public qui a l'lair plus intéressé par le conférencier ). Quelle est la taille exacte requise pour les photos (hauteur et largeur)? Je donnerais ces indications à la personne qui va les retoucher. 

Hélas, cette première photo est employée à divers endroit dans le site, ce qui entraînera un "re-travail" de montage. Si cela a un impact sur l'échéance globale et sur les heures de travail utlisées, on l'assume, d'autant plus que je n'aurai les nouvelles photos aujourd'hui, mais je ne sais pas quand le monteur aura terminé son travail. Pour les version dérivées de la photo empoyées ailleurs dans le site pourraient être remplacée par des images disponible dans notre banque d'images sur Google Drive, notamment la statut d'Hérodote.

**Comment by alberto56** [comment]
Je réouvre ce billet et j'ai ouvert aussi une nouvelle tâche #14

**Comment by yanic1665** [comment]
D'autres photos sont attendues de la part de collègue pour alimenter le site, notamment pour remplacer la première photo du carrousel de la page d'accueil (et ses formats dérivés un peu partout dans le site), à la suite de commentaires reçus de la part de l'exécutif. J'ai dû faire un noucel appel à tous aujourdhui et j'attends de novuelles photos idéalement d'ici mardi prochain (24 mars) à midi, avant notre réunion téléphonique.
