### ISSUE TITLE
Décider quel compte sera l'administrateur principal (propriétaire) de l'accès CMS (lien entre interface administrative et le site web)) (par défaut: Albert)

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#40]

**Comment by yanic1665** [comment]
Note de Albert: Pour faire suite à #26, il faut déterminer quel compte sera propriétaire du site car ce compte aura accès complet aux comptes des utilisateurs, c'est comme ça que Netlify fonctionne... Donc APHCQ devra avoir le contrôle de ce site.

**Comment by alberto56** [comment]
Noter comment ça marche actuellement dans le guide administratif.

**Comment by alberto56** [comment]
[J'ai documenté ça dans la section technique du guide](https://github.com/aphcq-association/site-web/commit/0763e30e73e766be7aa3fb6a636da9c90822be5a); je ferme ce billet.

**Comment by yanic1665** [comment]
Noté. Je viens de faire un copier-coller des deux parapagrahes d'explicatio
que tu as ajoutés à la fin du guide en lign,  afin de pouvoir les mettre
dans le fichier Google Docs que j'ai créé pour la mise à jour du guide (à
la section 1):

https://docs.google.com/document/d/13Inihw7bXeSPndsLqAqtF_xzhsL-Y-LSToGo9lZjzAE/edit#

Le mar. 7 avr. 2020, à 18 h 18, Albert Albala <notifications@github.com> a
écrit :
