### ISSUE TITLE
Backend: déterminer quel compte sera propriétaire du site

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#42]
Pour faire suite à #26, il faut déterminer quel compte sera propriétaire du site car ce compte aura accès complet aux comptes des utilisateurs, c'est comme ça que Netlify fonctionne... Donc APHCQ devra avoir le contrôle de ce site.

**Comment by yanic1665** [comment]
Cette tâche dédouble la tâche #40 . Je la ferme donc.
