### ISSUE TITLE
Guide pour l'administraiton du site web à l'intention de l'exécutif  (y intégrer la version de Yanic

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#43]

**Comment by alberto56** [comment]
Le guide admin est une page comme une autre sur le site et peut être modifiée dans le CMS au http://aphcq.dcycleproject.org/admin/#/collections/pages/entries/guide-admin, comme dans la capture d'écran ci-jointe.

<img width="516" alt="Screen Shot 2020-03-31 at 11 44 53 AM" src="https://user-images.githubusercontent.com/808265/78046481-32c60f80-7345-11ea-99d8-814890a57e51.png">

Je t'invite a y ajouter des consignes pour l'équipe, ou noter dans ce billet ou un autre si tu aimerais que j'y ajoute quelque chose.

**Comment by yanic1665** [comment]
OK, merci

Le mar. 31 mars 2020, à 11 h 46, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
@alberto56  La page où se trouve guide d'administration du site est actuellement accessble au public. Comment la réserver aux adminsitrateur du site? J

**Comment by alberto56** [comment]
@yanic1665 

> La page où se trouve guide d'administration du site est actuellement accessble au public. Comment la réserver aux adminsitrateur du site? J

Même si le code source est visible à la planète, seulement certains comptes peuvent _modifier_ le compte source, dont les administrateurs. Si quelqu'un n'ayant pas accès en écriture au code source tente de se connecter à la section administrative, elle voit ce message:

<img width="480" alt="Screen Shot 2020-04-03 at 9 05 13 AM" src="https://user-images.githubusercontent.com/808265/78363837-76f62180-758a-11ea-91d9-dddd72e556a1.png">

**Comment by alberto56** [comment]
Pour ce qui est du guide d'administration, comme tout le code source, cette page est accessible au public. Voici quelques idées de ce que l'on pourrait faire:

* Nous pourrions éviter que la page soit indexée par les engins de recherche
* Nous pourrions retirer le lien en bas de page qui mène vers cette page (dans lequel cas même les administrateurs devraient faire un signet avec l'URL exact du guide, donc certaines personnes pourraient "oublier" c'est où)
* Nous pourrions mettre un thème plus sobre, comme si c'était une section technique
* Nous pourrions la retirer complètement du site et la laisser uniquement sur GitHub.

Mon avis personnel est que ce n'est pas un problème que cette page soit publique. Plusieurs organismes rendent public des informations techniques.

**Comment by yanic1665** [comment]
Ma réflexion n'est pas encore terminée à ce sujet, mais si je réfléhis à
voix haute:

* [ ] 1. Oui, il faudrait éviter que le liens soit référencé par les engins
de recherche.
* [ ] 2.  Demande personnelle: je voudrais que mon nom n'apparaisse pas
dans les captures d'écran données en guise d'exemple comme c'est le cas
actuellement. Peut-on fair une capture d'un  autre projet?

Jecomrpens que laccès au code de la page n'est pas public, mais ce n'était
pas cela qui ne préoccupait.

À voir: Il est vrai que certaines personnes pourraient finir par oublier
l'URL de la page si jamais il n,y a pas de lien en bas de la page, mais:

a)  Je travaille sur un carnet d'adresse réservé aux membres de l'APHCQ qui
conteidnrai notamment cette infos (mais bon, je sais, ils pourraient même
oublier que ce carnet existe...
b) Ces mêmes personnes  pourraient aussi finir par oublier que cette page
est publique et y ajouter des informations confidentielles (noms
d'utilisateurs, nons ou courriels personnels d,individus). Je n'arrive pas
à décider quel risque est le plus grand...

Pour l'instant, conservons l'accès public à la page. Je vais en faire
mention dès le début de guide afin que ses utliisateurs s'en souviennent...

Yanic





Le ven. 3 avr. 2020, à 09 h 10, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
@yanic1665 j'ai [bloqué l'accès aux engins de recherches](https://github.com/aphcq-association/site-web/commit/730d3de225d4478fb201fd6c71f1e27f988ac498) et j'ai [retiré ton nom des photos exemples sur le site](http://aphcq.dcycleproject.org/guide-admin.html).

Pourrais-tu spécifier quelle option tu préfères:

* option A: on continue à travailler dans le Google Docs et quand c'est final on transfert [site le site](http://aphcq.dcycleproject.org/guide-admin.html).
* option B: on ne travaille plus sur le Google Docs, je transfert tout [sur le site tout de suite](http://aphcq.dcycleproject.org/guide-admin.html) et on continue les modifications sur le site [via Netlify](http://aphcq.dcycleproject.org/admin/#/collections/pages/entries/guide-admin) ou [GitHub](https://github.com/aphcq-association/site-web/blob/master/docs/guide-admin.html).

Si tu préfères option A, SVP me donner accès en écriture au Google Docs.

**Comment by yanic1665** [comment]
@alberto56  Les deux options me conviennent, mais je pencherais du côté de l'option A. Un peu plus rapide pour moi pour faire des retouces au besoin. Je vais massurer de valider tes derniers changement rapidement. 

Je viens de te partager l''accès au fichier en mode écriture. As-tu un compte Gmail? Ça en prendrait un. Sinon, je dois accorder un ddroit de modifcation à tous les détenteurs du lien. Or: le lien aparaît dans le présent billet + Tout le mone a accès au présent billet = L'humanité au complet pourrait modifier le fichier Google Docs .Un exempeled'enjeu découlant d'une complète transparence du code...  :)

 J'ai souligné les éléments à valider en jaune, mais ne te gêne pas pour fair eun survol rapider à l'ensemble du document. J'ai tendance à rajoute rde spetite sprcisions destinées à un lecteur néophyte (ex.: défininiton de CMS, etc), c,est possible que j'enpropsoe d'autres.

**Comment by alberto56** [comment]
Finalement j'ai écrit une version du guide en intégrant le Google Docs au http://aphcq.dcycleproject.org/guide-admin.html

La différence fondamentale est que j'ai beaucoup simplifié, considérant que l'utilisateur lambda n'aura jamais à utiliser l'interface GitHub, tout sera fait avec NetlifyCMS
 
qui est légèrement différent du document Google. Je propose que http://aphcq.dcycleproject.org/guide-admin.html soit la version canonique et qu'on détruise, à terme, le Google Docs.

**Comment by yanic1665** [comment]
@alberto56 Merci pour tout.  La verison en ligne  sera donc la version canonique.

2 modifs suggéréees (désolé, pas le temps pour le faire ce pm, je suis en rencontre de cégep):

Section 1: les deux hyperliens sont inactifs

Section 5: C'est vrai que le commun des mortels ne voudra pas mettre à jour le site en modifiant les pages de code, mais afin que le guide soit réellement autoportant, j'njouterais quand même à la section 5 quelque chose équivalent à ce passage dans mon ancienne version du guide:

Code source du site web de l’APHCQ: distribué gratuitement sur la plateforme Github à https://github.com/aphcq-association/site-web

**Comment by alberto56** [comment]
* [x] Section 1: les deux hyperliens sont inactifs

* [x] Section 5: C'est vrai que le commun des mortels ne voudra pas mettre à jour le site en modifiant les pages de code, mais afin que le guide soit réellement autoportant, j'njouterais quand même à la section 5 quelque chose équivalent à ce passage dans mon ancienne version du guide: Code source du site web de l’APHCQ: distribué gratuitement sur la plateforme Github à https://github.com/aphcq-association/site-web
