### ISSUE TITLE
Langue de Paypal, doit être en français

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#44]

**Comment by yanic1665** [comment]
@alberto56  Le problème de la lanfue de confirmaiton des transaction PayPal se manifeste notamment dans le titre des courriels émis (voir pièce jointe)
![Capture d’écran, le 2020-04-02 à 18 43 35](https://user-images.githubusercontent.com/61343142/78307418-d06f3980-7513-11ea-99a7-0dd5c6f46e3e.png)

**Comment by alberto56** [comment]
SVP confirmer que votre compte PayPal est en français:

(1) aller dans:
https://www.paypal.com/businessmanage/account/accountPreferences

(2) confirmer que la langue est bel et bien "français".
<img width="1136" alt="Screen Shot 2020-04-03 at 9 32 11 AM" src="https://user-images.githubusercontent.com/808265/78366103-081ac780-758e-11ea-81a0-c7c58e02fb87.png">

Sinon changez la langue.

**Comment by yanic1665** [comment]
Demande transférée à la trésorière.

**Comment by alberto56** [comment]
Si vous voulez que je fasse la configuration tu peux me transférer le mot de passe par Signal.

**Comment by alberto56** [comment]
Ça semble marcher maintenant, je viens de faire une transaction d'un dollar

<img width="557" alt="Screen Shot 2020-04-08 at 9 15 55 AM" src="https://user-images.githubusercontent.com/808265/78788311-a1c0eb00-7979-11ea-9005-3244847273b9.png">

**Comment by yanic1665** [comment]
@alberto56 J'ai fait moi aussi le test. Tout est OK. Je ferme.
