### ISSUE TITLE
Photo de bannière de la page "Adhérez" à recadrer (remonter la photo vers le haut pour monter plutôt le centre de la photo) http://aphcq.dcycleproject.org/adherez.html

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#45]

**Comment by alberto56** [comment]
Ça devrait être beau au http://aphcq.dcycleproject.org/adherez.html

Et on peut changer ça dans le CMS

![Screen Shot 2020-04-08 at 8 55 53 AM png](https://user-images.githubusercontent.com/808265/78787774-dbddbd00-7978-11ea-8a68-3afd57995a73.jpg)

**Comment by yanic1665** [comment]
@alberto56  À inclure de façon brève dans le guide d'administration du site en #43. Je ferme le billet.
