### ISSUE TITLE
Problème de navigation dans la version mobile: quand on revient de la page "Adhérez" vers  la page précédent en utilisaant la flèche  "retour" du navigateur (ex.: Safari pour iPhone), le menu général du site habituellement en haut se retrouve subitement à guiche et masque ainsi la moitié du site.

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#46]

**Comment by alberto56** [comment]
Ceci semble le comportement normal en fait. Regarde l'image ci-jointe.

<img width="1066" alt="Screen Shot 2020-04-07 at 7 58 52 PM" src="https://user-images.githubusercontent.com/808265/78730278-502d4780-790a-11ea-8146-77e48cb1d139.png">

À l'étape 1 on déplie le menu, nous menant à l'étape 2, qui est le site avec le menu déplié, ensuite on se rend vers une page dans le menu, soit l'étape 3.

Cliquer sur "retour" dans le navigateur fait ce qu'on lui demande, soit revenir à l'étape 2 avec le menu déplié, et non l'étape 1. 

Visite par exemple le site du devoir au https://www.ledevoir.com, qui fonctionne de la même façon:

<img width="1139" alt="Screen Shot 2020-04-07 at 8 14 06 PM" src="https://user-images.githubusercontent.com/808265/78730999-6936f800-790c-11ea-8f77-0e44f2e5c885.png">

Il est intéressant de constater que le site d'Apple n'exhibe pas ce comportement, mais bon, là on parle d'une autre gamme de budget.

Voici un [article qui traite un peu de ce sujet](https://uxdesign.cc/an-approach-to-solve-complex-backward-navigation-in-mobile-through-user-research-45d786a83bed)... peut-être pour une phase 2 du projet! Je recommande de laisser tel quel

**Comment by yanic1665** [comment]
@alberto56  OK, laissons le site en état pour l'instant. J'ai toutefois copié tes explications dans un nouveau billet #53, dans lequel j'ai demarré une iaite de changements futurs possibles (qu'on peut alimenter d'autres suggesitons au besoin).

Je partage ta réponse avec @JPlourde1880 au cas où celle-ci aimerait commenter.
