### ISSUE TITLE
Problème d'affichage des caractères accentués des options Paypal dans l'avis de réception Paypal.

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#47]

**Comment by yanic1665** [comment]
@alberto56 Je viens d'adhérer à l'APHCQ en ligne en guise de test, et je constate que les caractères sorte bizarrement dans l'avis de réception Paypal. Il y a même un mot "Hello" qui s'ajoute:  "hello: CatÃ©gorie B - Membre rÃ©gulier non subventionnÃ©:"  Voir la capture d'écran.  Des suggestions de solutions?

[Capture d’écran, le 2020-04-01 à 14 27 54](https://user-images.githubusercontent.com/61343142/78174131-c3285100-7426-11ea-85b5-face97267493.png)

**Comment by alberto56** [comment]
Prochaines étapes:

* [ ] Je vais suivre les instructions au https://support.bookeo.com/hc/en-us/articles/360017924152-How-to-set-the-correct-character-encoding-in-PayPal
* [x] Aussi, au lieu de "test" je mettrai quelque chose avec des caractères accentués pour ne pas être obligé de faire un achat complet pour chaque test.
* [x] Le mot "hello" avait été entré comme test. Je le rendrai configurable.

**Comment by yanic1665** [comment]
Parfait, merci.

Le jeu. 2 avr. 2020, à 07 h 38, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Vous devez faire quelque chose sur votre compte:

(1) aller dans https://www.paypal.com/cgi-bin/customerprofileweb?cmd=_profile-language-encoding

(2) cliquer sur more options

(3) dans encoding, choisir UTF 8 et faire Save 

<img width="1041" alt="Screen Shot 2020-04-03 at 9 30 08 AM" src="https://user-images.githubusercontent.com/808265/78366203-284a8680-758e-11ea-878b-1e297e2cd23a.png">
<img width="792" alt="Screen Shot 2020-04-03 at 9 30 48 AM" src="https://user-images.githubusercontent.com/808265/78366209-2aace080-758e-11ea-9d53-6f5d04ac6d51.png">

**Comment by yanic1665** [comment]
Demande acheminée à la trésorrière le 3 avril 2020.

Le ven. 3 avr. 2020, à 09 h 35, Albert Albala <notifications@github.com> a
écrit :

**Comment by alberto56** [comment]
Ça semble marcher maintenant, je viens de faire une transaction d'un dollar

<img width="557" alt="Screen Shot 2020-04-08 at 9 15 55 AM" src="https://user-images.githubusercontent.com/808265/78788311-a1c0eb00-7979-11ea-9005-3244847273b9.png">
