### ISSUE TITLE
Procéder au 2e versement des honoraires au développeur

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#49]

**Comment by alberto56** [comment]
Pour info:

Lors du premier paiement, il y a un surplus de 75$

En fait une erreur s'est glissée dans le calcul de la TPS qui aurait dû lire 75$ et non 150$.

Le 75$ que vous avez payé en trop sera déduit de votre prochain paiement.

La prochaine facture sera donc de 1724.63$ mais **vous paierez  seulement 1649.63$.**

Ça peut se faire lors de la mise en ligne du projet

**Comment by yanic1665** [comment]
@alberto56  Bien noté, merci. J'avise la trésorière.

**Comment by yanic1665** [comment]
@alberto56  Notre trésorière attend ta facture pour procéder au second et dernier versement des honoraires.

**Comment by alberto56** [comment]
J'ai envoyé la facture et les infos à Julie.

**Comment by yanic1665** [comment]
@alberto56  Petiti suivi: as-tu reçu le second paiement d'honoraires?

**Comment by alberto56** [comment]
Salut, je confirme que tout est complet, j'ai reçu le dernier paiement le 17 Apr 2020 de 1,649.63. 

Merci encore!

**Comment by yanic1665** [comment]
Super, merci!
