### ISSUE TITLE
Adresse postale pour facturation obtenue

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#5]
Julie Plourde (trésorière) a indiqué le 24 février  attendre la facture du développeur pour faire le premier versement de honoraires par virement bancaire. Adresse personnelle (qui sert pour la correspondance financière de l'AHCQ en 2019-2020: 7343 rue Boyer, Montréal (Québec), H2R 2R6.

**Comment by yanic1665** [comment]
Albert, est-ce que tu as bien reçu le premier versement des honoraires?

**Comment by alberto56** [comment]
Oui, c'est confirmé, merci. Je ferme ce ticket.
