### ISSUE TITLE
Changer le domaine du site pour le rendre public

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#50]

**Comment by alberto56** [comment]
* [x] Partout dans le code, changer le url de aphcq.dcycleproject.org pour aphcq.ca
* [x] Retirer le CNAME du vieux site
* [x] Changer le CNAME du nouveau site

**Comment by alberto56** [comment]
à faire quand on est prêt à rendre le site public

**Comment by yanic1665** [comment]
@alberto56 Je te confirme que tous les commentaires sur le site reçcus de la part de l'exécutif ont traités (une seule petite correcitn lingusutique fut requise). Le site est donc complet et terminé en ce qui nous concerne. Nous pourrionsdonc djéà procder à samise en ligine, mais j'aimerais attendre a réunion de 'exéctif, qui se réunit demain soir 19h. Peut-on convenir d'une mise en ligne vers 19h00?

**Comment by alberto56** [comment]
OK appelle-moi vers 18h30 on le fera ensemble.

**Comment by yanic1665** [comment]
@alberto56 Parfait!

**Comment by yanic1665** [comment]
@alberto56  Les membres de l'exécutif ont testé le nouveaus site. Bravo et merci encore! Tout le monde es tbien content.

On constaté par ailleurs  deux problèmes:

* [ ] 1. Dans les "sous-liens" dans la page des résultats du moteur de recherche Google, les hypersliens qui devraien tmener à des pages précises du site mène plutôt à des  messages  d'erreur "404" (voir capture d'écran). Est-ce normal?

* [ ] 2. Parmi ces sous-liens, on retrouve la page "Activités", qui a été repertoriée par Goolge alors que nous ne souhaitons pas l'utiliser (voir capture d'écran). Nous aimeriosns qu'elle soit retirée. Est-ce posible?
![Capture d’écran, le 2020-04-15 à 21 55 07](https://user-images.githubusercontent.com/61343142/79406194-65d2ea80-7f64-11ea-9972-b32ac90d5676.png)
![Capture d’écran, le 2020-04-15 à 21 54 56](https://user-images.githubusercontent.com/61343142/79406207-6ec3bc00-7f64-11ea-9e41-c6fee75a4338.png)

**Comment by alberto56** [comment]
* [x] j'ai changé toutes les instances de aphcq.dcycleproject.org à aphcq.ca dans le code
* [x] j'ai fait une bell page non-trouvée plutôt que la page par défaut github, voir par exemple: https://www.aphcq.ca/ceci-nexiste-pas
* [x] j'ai fait une recherche google et pour toutes les pages référencées qui ont changé de nom, j'ai fait une redirection. Tout devrait y être, mais au besoin, voici comment faire une redirection: faire un nouveau fichier dans github et y mettre par exemple:

```
    ---
    layout: redirect
    redirect: https://www.aphcq.ca/bulletin.html
    ---
```

[voici un exemple](https://github.com/aphcq-association/site-web/blob/master/docs/asso.htm) qui redirege /asso.htm vers https://www.aphcq.ca/apropos.html.

* [x] pour la page activités, elle devrait bientôt redireger vers la page d'accueil ou une page non-trouvée, et les engins de recherches la retireront donc de leur liste de page bientôt.

**Comment by yanic1665** [comment]
@ Merci pour les modifications. Le liens des pages "Activités" et "Documents" (nouvellement apparue), dans la page des résultats de Google, renvoient désormais à la page d'accueil du site.

**Comment by yanic1665** [comment]
@alberto56 Albert, si jamais on voulait redirigier vers notre site les internautes qui taperaient par erreur l'adresse "aphcq.qc.ca" ou autre, est-ce que: 
1. ça implique de louer les noms de domaines "erroné"s auprès de nore founrisseur?
2. c'est facile à faire (au point que nous puissions le faire nous-même)?

**Comment by alberto56** [comment]
Il faut louer un nom de domaine avec un fournisseur, et sur l'interface administrative, faire une redirection vers https://www.aphcq.ca. Si cela s'avère impossible, on peut toujours ouvrir un nouveau projet sur github qui servira uniquement à faire la redirection vers le domaine canonique [comme c'est suggéré dans cet article](https://stackoverflow.com/questions/16454088/can-github-pages-cname-file-contain-more-than-one-domain). C'est simple si on connaît ça, sinon ça prend un peu d'essai-erreur!

**Comment by yanic1665** [comment]
@alberto56  OK, merci des précisions!
