### ISSUE TITLE
Faire une copie de sauvegarde du site web sur un disque dur personnel.

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#51]

**Comment by alberto56** [comment]
Pour faire une copie de sauvegarde du code, tu peux aller https://github.com/aphcq-association/site-web, ensuite cliquer Clone or Download, ensuite Download ZIP, comme dans l'image ci-jointe.

<img width="1025" alt="Screen Shot 2020-04-07 at 8 18 20 PM" src="https://user-images.githubusercontent.com/808265/78731200-0a25b300-790d-11ea-99d8-c261d534878d.png">

**Comment by yanic1665** [comment]
@alberto56 Je pourrais m'occuper de cette tâche, mais  je voudrais ton avis:
- Est-ce excessif comme mesure de sécurité?
- Est-ce que ça rsique d'occuper beaucoup d'espace sur un disque dur?
- Aurais-tu une suggesitond d'appli en Mac pour ce faire (ex.:  SiteSucker)?
- Pensais-tu en faire une copie sur ton serveur personnel (er devrais-je le faire moi aussi quand même)?

**Comment by alberto56** [comment]
> Est-ce excessif comme mesure de sécurité?

Dans mon expérience rien n'est jamais excessif. Toutefois, une décision de faire une copie locale du site, doit, dans mon expérience, s'accompagner de politiques:

* de mises à jour de la copie de sauvegarde selon un calendrier préétabli, de façon automatisée ou encore avec un rappel dans l'agenda, pour que la copie locale reflète la copie principale non seulement au moment de la première copie de sauvegarde mais tout au long de la durée du vie du projet.
* de tests de la copie de sauvegarde, c'est à dire s'assurer que la copie de sauvegarde est réellement utile en cas de perte de la copie principale.

> Est-ce que ça rsique d'occuper beaucoup d'espace sur un disque dur?

Il y a deux parties au site:

* la partie "code sous-jacent", qui est de 271.2 Mo, donc pas insignifiant. Cette partie est qui existe sur GitHub si tu télécharges le ZIP. Toutefois ce code est inutile à la moins de l'utiliser pour "générer" un site web. Ceci peut se faire en suivant les instructions techniques au https://github.com/aphcq-association/site-web, dans la section "Développement local", ce qui savoir comment naviguer dans l'ordinateur en utilisant le "terminal".

* Le site "généré" à partir du code sous-jacent, qui est automatiquement recréé par GitHub à chaque fois qu'un changement est fait, et qui être généré sur ton ordinateur au besoin en suivant les instructions. Cette partie fait 136 Mo. 

> Aurais-tu une suggesitond d'appli en Mac pour ce faire (ex.: SiteSucker)?

Site Sucker est très utile et peu cher pour faire une copie locale de n'importe quel site, donc celui-ci. D'autres applis eet approches sont:

* L'application Mac de GitHub, qui permet de garder plus facilement à jour le code locale selon le code distant. Ce n'est toutefois pas une automatisation complète et ça ne permet pas de "générer" le site.
* La fonction "Fork" en haut à droite de l'interface "GitHub" (je vois que tu l'as déjà fait) qui permet de faire une copie du code, mais sur les serveurs de GitHub. Ceci te protège un peu si l'espace de APHCQ disparaît. Toutefois ça ne te protège pas si ton compte et compromis et une personne malveillante efface toutes les données auxquelles tu as accès.

> Pensais-tu en faire une copie sur ton serveur personnel (er devrais-je le faire moi aussi quand même)?

Ma politique de copies de sauvegarde pour les projets JAMStack (dont APHCQ), donc les projets où le code est autosuffisant et inclut tout le contenu, est de faire une copie automatiquement une fois par semaine sur un serveur [Jenkin](https://jenkins.io) dans le "nuage" hébergé sur [DigitalOcean](https://www.digitalocean.com) (région de New York). Chaque semaine aussi, des tests sont roulés pour confirmer que le code est utilisable. Et de plus un backup hebdomadaire de mon serveur Jenkins. Je ne garantis pas de garder une copie sur ordinateur toutefois.

Pour tout perdre, il faudrait que le code disparaisse en permanence de GitHub, de mon serveur Jenkins et du backup de mon serveur Jenkins. C'est possible mais peu probable.

De toute façon, c'est une bonne pratique de ne jamais te fier à une seule entité (incluant moi!) donc, oui, je te recommande de faire une copie locale.

**Comment by yanic1665** [comment]
@alberto56 Merci de toutes ces précieuses explciaitons et tptions possibles. Je ne pensais pas ici à une copie local qui serait faite par l'Associaiton sur une base régulière (je n'y cori spas vriament), mais à une simple copie unique  qu eje ferais perosnnellement, pour ma saitsfaction et tranquilité d'esprit personnelle. Je ne sus pas ferm é à la faire avec Github, mais par facilit, je rsique deme rebattre faire SiteSucker ou équivalent, même si cela peut compliqu cetaines tâches ensuite, vu les autres sauvegardes que tu mentionnes.
