### ISSUE TITLE
Courte citation à mettre sur le site de Dcycle (optionnel)

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#55]
Normalement je travaille avec des équipes préétablies sur des projets de plusieurs années, et donc je ne fais pas normalement de publicité (je n'ai même pas de vrai site web pour mon offre de création de site web, selon le principe de "cordonnier mal chaussé".)

Toutefois j'aimerais dans la prochaine année offrir un service de "petit site web" comme on vient de faire pour APHCQ. Et donc, si APHCQ veut bien, j'apprécierais une courte citation du genre: 

"La communication a été bonne tout au long du projet, et le site a été livré à temps selon nos attentes"

Que je pourrais attribuer à APHCQ sur un éventuel site web pour décrire ce service.

Bien sûr ceci est tout à fait optionnel!

**Comment by yanic1665** [comment]
@alberto56  Je n'y voi saucunproblème a priori, je vais jsute valide avec l'exécutif

**Comment by yanic1665** [comment]
@alberto56 L'excutif de l'APHCQ est d'accord à ce que tu mentionnes l'Association comme l'un de tes clients dans ton site.
