### ISSUE TITLE
Décrire les photos pour les personnes non-voyantes

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#56]

**Comment by alberto56** [comment]
J'ai ajouté un champs "Description de la photo" sur toutes les photos (ou la plupart des photos -- si tu trouves champs "photos" qui n'ont pas ce champs, tu peux les décrire ici).

Voir la capture d'écran ci-jointe qui correspond à la page de modification de la page "Adhérez".

<img width="875" alt="Screen Shot 2020-04-08 at 8 34 04 AM" src="https://user-images.githubusercontent.com/808265/78784816-0711dd80-7974-11ea-897d-d053ed6bbea9.png">

Je vous recommande fortement de remplir ces champs à l'intention des personnes non-voyantes. Ce n'est pas une exigence légale (comme par exemple pour les sites gouvernementaux) mais c'est une façon simple de penser aux visiteurs non-voyants.

**Comment by alberto56** [comment]
Et oui, il manque un "s" à personnes, je corrige ça.

**Comment by alberto56** [comment]
Le CMS permet dorénavant de décrire les photos pour non-voyants, je propose donc de fermer ce billet.

**Comment by yanic1665** [comment]
@alberto56  J'ai ajouté une nouvelle section à ce sujet dans le guide administratif: http://aphcq.dcycleproject.org/guide-admin.html#3.7
