### ISSUE TITLE
Faire ouvrir la page Facebook dans un nouvel onglet lorsqu'on clique sur le lien "Sur Facebook, dans la menu supérieur.

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#57]

**Comment by yanic1665** [comment]
@alberto56  Le changement a été pour le lien ves Facebook dans le mue supérieur du site, mais pas pour le lien à partir de la boite orange de la page d'accueil, qui ne s'ouvre pas dans un onglet différent. Serait-ce possible d'y voir ?

**Comment by yanic1665** [comment]
Bille fermé par erreur  il y quelques instant. Je viens de le rouvrir

**Comment by alberto56** [comment]
OK regarde dans quelques minutes ça devrait marcher.

**Comment by yanic1665** [comment]
@alberto56 Merci, ça marche!
