### ISSUE TITLE
1ere photo du caroussel lente à télécharger

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#58]
La première photo du carrrousel dans la page d'accueil est toujours asse lente à télécharger, même une fois qu'on est déjà dans le site qu'onpasse duen page è lautre. Y aurait-il moyen de compresser le fichier ou autre?  Ce la n,est pa sidéal pour l'image du ste, puisque c,est le première chose que constate un visiteur en accédant à la page.

**Comment by alberto56** [comment]
OK je peux le faire, voir aussi la section "Attentions aux photos trop lourdes" dans aphcq.dcycleproject.org/guide-admin.html

**Comment by yanic1665** [comment]
@alberto56  OK, je viens de faire le changement moi-même,  partir d'une version compressée à 77% de la photo en question (fichier nommé "6c.jpg"). Le problème es tocn réglé

Au fait, note que dans la seciton CMS du carrousel, les onglets correspondant è chaucne de sphtos du carrousel portent tout désormais la mention "No titre" plutpôt qu'un titre précis, car ce champs affiche par défaut ce qui est écrit dans le champ  "Titre (optionnel) du formulaire et nous avons finalement décidé de ne pas utiliser ce champs. Ça ne me cause pas problème personnellement, mais un nouvel utilisateur pourrait trouver ça bizarre ou penser à première vue que le donnéess ont été accidentellement effacées .

S'il Ny a rien  faire pour régler ce problème, laissons en état. Tu peux alors fermer le billet.

**Comment by alberto56** [comment]
T'as raison, puisqu'on n'utilise jamais le titre, je l'ai enlevé et lors du prochain déploiement, le "sous-titre" devrait faire office de titre.
