### ISSUE TITLE
Page "Bulletin": liste des numéros en remettre en non-gras

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#59]
Merci du montage-photo des numéros du Bulletin dans la page "Bulletin de l'APHCQ". Concept intéressantt. Si je peu peux me permettre un commentaire: la mutlplicaiton des petites icônes les rend touteofis difficile sà lire, et ça suggère intuituivement des incônes clicables qui permettraient d'accéder aux numéros du Bulletin (ce qui n'est pa sle as ni l'intention ici). J'ai moi-même imméaitement cloqu dessus sans tip y réfléchor lorsque j'ai accédé à la page.  Loin de moi l'idée de te générer du trvaail supplmentaire ou de vouloir "défaire" ton travail, mais ne serait-ce pas plus simple finalement de me mettre qu'un seule page couverture de bulletin en guise d'image. je recule un peu pa rappor tà mo idée originale, mais je pense que ce serait mieux visuellement.  Par exemple: 
https://drive.google.com/drive/folders/1cynxYHdj2AYfeIVpGp7aglGhWw28MkmW
Je reviens à la charge

**Comment by alberto56** [comment]
En fait c'était pas trop de travail, j'ai juste pris une capture d'écran de la liste de bulletins sur mon ordi. Pour le moment puis-je proposer de mettre une autre image avec le CMS et de bouger cette tâche vers une éventuelle phase 2?

**Comment by yanic1665** [comment]
@alberto56 Je viens de faire le changement. On se contentera d'un seule exemple de page couverture (même pas besoin de mettre ça dans une phase 2 selon moi).

**Comment by yanic1665** [comment]
@alberto56  Une question: tous le numéros du Bulletin dans la page http://aphcq.dcycleproject.org/bulletin.html apparaissent déromais en gras,  sauf pour le volume 26. Es-tce normal? Peut-on remettre en non-gras STP.

**Comment by yanic1665** [comment]
@yanic1665 . Merci, je ferme.
