### ISSUE TITLE
Éliminer l'option de paiement "test" dans Paypal

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#6]
* [x]  1. Julie: Attendre l'autorisation de Paypal pour pouvoir faire des transferts puisque le compte est nouveau (avis indiquant un délai de "2 à 3 jours" affiché  depuis une semaine...). 

* [x]  2. Julie: Faire un transfert de fond test vers Desjardins 

* [x]  3. Demander à un membre de l'exécutif d'adhérer en bonne et due forme afin de tester la gestion du formulaire d'adhésion et le menu Paypal (réception des données dans le calsseur et transfert manuel vers la liste de membres); Faire des mises à jour au besoin (avec Yanic). 

* [ ] 4. Une fois les tâches précédentes complétées, éliminer l'option de paiement "Test 1,00$" dans le menu déroulant Paypal.

* [x]  5. Julie: Créer un nouveau poste budgétaire dans le budget annuel afin d'assurer les frais de gestion de Paypal. Selon https://www.paypal.com/ca/for-you/fees, les frais sonr de 
frais de 2.9% + $0.30 CAD par transaction

* [x] 6. Julie: concevoir une procédure  maison d'émission de reçus lors des adhésions à l'APHCQ via la site (adhésion en ligne ou par la poste).

**Comment by alberto56** [comment]
@yanicviau j'ai envoyé un message à Julie:

> L'identifiant du compte PayPal est l'adresse courriel qui y est associé.
> En aucun cas ne transmettez des mots de passe par courriel, l'adresse courriel me suffira.

**Comment by alberto56** [comment]
@yanicviau le compte paypal semble fonctionner. 

[Les options d'achat peuvent être mis ici](https://github.com/aphcq-association/site-web/blob/master/docs/_config.yml#L6-L14). Vous pouvez changer au besoin.

Sur [cette page](http://0.0.0.0:8081/2020/03/10/congres-2020.html) il y a un bouton paypal avec toutes les options.

Pour le moment j'ai mis une option à 10 cents pour faire des tests, et j'ai fait un achat avec succès, pourrais-tu confirmer que vous avez reçu l'argetn?

**Comment by yanic1665** [comment]
Salut Julie,

Nous venons de faire une transaction-test  de 0,10$ vers le compte Paypal
de l'APHCQ (voir message ci-bas). Peux-tu vérifer STP que ça a bien été
reçu et nous le confirmer en faisant un "réponse à tous" au présent
courriel?

Merci,

Yanic

P.S. J'aurais aussi besoin que tu me communiques le mot de passe de
connexion à Paypal pour nos archives, mais en l'envoyant un message
distinct ou par unmoyen de communicaiton différent pour des raisons de
confidentialité.

Le mar. 10 mars 2020, à 14 h 56, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
Bonsoir,

J'ai bien reçu le paiement. Par ailleurs, il ne s'affiche pas dans l'argent
disponible au compte puisque des frais de 0.10$ sont chargées à chaque
transaction. Pour le prochain test, je pourrai peut-être tenter un paiement
plus gros (genre un gros 0.20$). J'aimerais tenter de comprendre comment
transférer l'argent du Paypal dans notre compte Desjardins avant le
congrès.

Pour le mot de passe, Yanic, nous pourrons en discuter à la prochaine
réunion. Je pense, personnellement, qu'il serait mieux que le mot de passe
se transmettre exclusivement entre trésorier-ère.

Bonne soirée,

Julie

**Comment by yanic1665** [comment]
Bien reçu Julie!

Oui à un test de 0,20$ pour transférer ensuite l’argent chez Desjardins. Albert: tu t’en charges ou tu nous donne le lien pour qu’on le fasse. 

Et oui à la confidentialité du mot de passe, à conserver entre les mains de la trésorière. Bien d’accord!

Yanic

**Comment by alberto56** [comment]
Bonjour, j'ai [modifié de 10 à 20 cents le test](https://github.com/aphcq-association/site-web/commit/462ba28281da7e931fd3a9a77abd2396a0dedddd), vous pouvez y avoir accès au http://aphcq.dcycleproject.org/2020/03/10/congres-2020.html pour le paiement.

Pour transférer de l'argent de PayPal à Desjardins, [voici un article qui pourrait vous aider](https://zone.votresite.ca/commerce-electronique/paiement-en-ligne/ouvrir-un-compte-paypal-et-le-lier-a-votre-compte-bancaire/I6o3twe8gg/).

Si vous avez ouvert un compte entreprise, PayPal vous demandra probablement des documents justificatifs avec le nom de votre association, votre enregistrement, etc. Je vous conseille de vous y mettre assez tôt car cela peut prendre longtemps (donnez-vous deux semaines). Si vous avez besoin d'aide avec ça, lassez-moi savoir.

Finalement, pour le mot de passe, SVP ne jamais transmettre à quiconque des mots de passe par courriel ou via GitHub; je vous conseille d'utiliser une application sécurisée comme Signal sur votre téléphone pour transférer des données confidentielles, puis effacer les messages au fur et à mesure.

**Comment by yanic1665** [comment]
Bien que ce ne soit pas une tâche directement reliée à la conception du site, prends note que la trésorière Julie Plourdre termine actuellement la configuraiton du compte Paypal afin de pouvoit tester le transfert de fonds de Paypal versle compte bancaire de l'APHCQ. Paypla a reçu le paiment test, mais encore faut0il le retransférer vers le comtpe bancaire. Julie nous reviendra (17 mars0

**Comment by yanic1665** [comment]
Une relance a été faite par Yanic le 22 mars auprès de Julie Plourde pour savoir si la transaciton test est bel et bien complétée.

**Comment by yanic1665** [comment]
Abert, nous ne voyons toujours pas dans le compte Paypal le deuxième paiement-test de 0,20$ que tu a fait le 11 mars. Peux-tu vérifier que tout est OK de ton côté? Il se peut peut uq ele problème soit de notre côté, mais nous procédons par élimination.

Par ailleurs, nous attendons toujours de la part de Paypla une confirmation de répeption de infos qui étaient manquantes pour pouvoir bien identifier l'administratrice du compte, et ainsi pouvoir ensuite rediriger les fonds vers notre compte bancaire. Le message d'avis parle d'un "délai de 2 à 3 jours", mais cela fait plus d'une semaine que ça dure. À suivre.

**Comment by alberto56** [comment]
@yanicviau je n'ai pas fait de transfert, j'ai simplement modifié la liste pour permettre un transfert de 20 cents. Toutefois selon https://www.paypal.com/ca/for-you/fees les frais sont de 2.9% + $0.30 CAD par transaction. Donc 20 cents c'est pas assez. Je viens de [mettre 50 cents au lieu de 20 cents](https://github.com/aphcq-association/site-web/commit/9491ba9f2cde8623321a8d596653c9881584c679) pour être (plus) sûr qu'il reste quelque chose après les frais.

Je viens aussi de faire un achat de 50 cents au http://aphcq.dcycleproject.org/adherez.html

Vous pouvez essayer aussi si vous voulez.

Voici mon reçu

<img width="451" alt="Screen Shot 2020-03-23 at 3 16 56 PM" src="https://user-images.githubusercontent.com/808265/77354541-6091cf80-6d19-11ea-9c03-269f700b8215.png">

**Comment by alberto56** [comment]
(je crois que c'est en anglais car MON compte PayPal a pour langue principale l'anglais, toutefois je vous encourage à essayer pour être sûr que c'est en français pour vous)

**Comment by alberto56** [comment]
Voici mon reçu par email

<img width="578" alt="Screen Shot 2020-03-23 at 3 18 28 PM" src="https://user-images.githubusercontent.com/808265/77354686-a0f14d80-6d19-11ea-8c78-246bb779d930.png">

**Comment by yanic1665** [comment]
Merci Albert des précisions, je les fais suivre à Julie. J'avais mal
compris et nous étions donc vianement en attente de ce second
paiement-test... Je vais l'essayer aussi (RECTIFiCATION: avec un paiement de 0.50$ et non 1,00$).

Yanic

Le lun. 23 mars 2020, à 15 h 17, Albert Albala <notifications@github.com> a
écrit :

**Comment by yanic1665** [comment]
Par contre la page douvetture de Paypal qui appraît après avoir choisi l'option de paiement apparaît en anglais pour moi aussi (bien qu'il y ait un bouton por changer de langue au bas de la age).. Julie, peux-tu véririfer nos configyrations de compte pour voir si on ne pourrait pas choisir le français par défaut? Cela m'apparaît important.

**Comment by yanic1665** [comment]
Et une fois que le paiement est fait et que l'avis de confrmation est reçu, il n'y a pas de bouton qui permet de revenir au site de l'APHCQ (à moins d'utiliser les flèches du navigateur). Julie, il faudrait explorer les options possibles de ce côté lorsque tu auras un peu de temps. Ce n'est pas primordial mais ça faciliterait les choses aux uitlisateurs

Yanic

**Comment by yanic1665** [comment]
@alberto56 Il ne reste plus ici qu"à éliminer l'option de paiement "Test " dans le menu déroulant Paypal.

**Comment by alberto56** [comment]
On le fera ensemble ce soir à la formation.
