### ISSUE TITLE
Enjeu: Quelle sera l'adresse visible du site une fois public?

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#60]
Est-ce que ',adresse du site qui serait visible dans la barre d'adresse par les utilisateurs sera http://aphcq.dcycleproject.org/ ?
Que se passera-til alors si jamais on change de développeur ou de serveur?

**Comment by alberto56** [comment]
Non une fois qu'on fait le transfert, l'adresse sera aphcq.ca

**Comment by yanic1665** [comment]
@alberto56 Merci!
