### ISSUE TITLE
boutons du carrousel cachent le texte

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#62]
<img width="279" alt="Screen Shot 2020-04-09 at 1 50 13 PM" src="https://user-images.githubusercontent.com/808265/78925197-0c9d1f80-7a69-11ea-9318-32e502371a54.png">

J'ai bougé les flèches plus haut, si t'as d'autres idées laisse-moi savoir.

**Comment by yanic1665** [comment]
@alberto56  C'est bon!
