### ISSUE TITLE
Demander au développeur une liste-type des étapes (aide-mémoire des tâches) pour la conception d'un site web.

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#63]

**Comment by alberto56** [comment]
Salut, il me fera plaisir de fournir une telle liste, toutefois, donnez-moi un peu plus de détails de ce que vous voulez et la raison-d'être d'un tel document.

**Comment by yanic1665** [comment]
@alberto56  Il s'agit davantage d'un aide-mémoire personnels, dans le cas où j'aurai à gérer la concpetion d'un autre site web. Le degré de précisions techniques n'a pas  être très détaillé. L'idée n'est pas de générer un nouveau document ex nihilo, ça pourrait être une sorte de synthèse des tâches que vous avons réalisées à  ce jour, sous forme d'ébauche ou dans un tysle télégraphique (je pourrais moi-même formaliser ou éditeur la documet par la suite ). Cet outil pourrait aussi te servir: tu pourrais le proposer à des clients futurs peu familiers des étapes requises pour un tel projet. J'ai d'abord pensé partir de la liste de tâches "finies" dan sle projet, mais: 1, Ce n'est pas évident de faire un cpier-coller;  2. Les tâches ysont de niveau hiérarchiques très variables (aves plusieurs points de détails), et 3. la liste me semble incomplète, certaines tâches se trouvant plutôt dans les billets dans les faits.

**Comment by alberto56** [comment]
OK, voici ce qui me vient en tête. Toutefois notons que chaque projet est réellement très différent, il est donc difficile de distiller tout ça en un checklist universel. Mais voici les étapes principales:

* S'entendre avec le client sur une description des spécifications d'**une seule page** (plus qu'une page, c'est trop de détails).
* Désigner une personne-ressource qui gère le projet du côté du client, et une personne-ressource du côté du fournisseur. Ces personnes seront conjointement responsables d'accepter les tâches (fermer les billets) et respecter l'échéancier.
* S'entendre sur des rencontres hebdomadaires d'à peu près une heure où seront présents au minimum le représentant du client et le représentant du fournisseur.
* S'entendre sur (a) une technologie (exemple: netlify/jekyll pour nous), (b) un fournisseur d'hébergement (exemple: github pages pour nous), (c) un hébergeur pour le code (exemple: github pour nous) (d) un système de gestion de projet (exemple: le système de billets de Github), le tout dès le tout début (en fait la plutpart de ça devrait être dans le devis / contrat pour éviter des malentendus).
* **Le plus tôt possible, idéalement dans la première semaine** mettre en place un environnement fonctionnel (dans notre cas c'est http://aphcq.dcycleproject.org). Les tâches seront considérées terminées une fois qu'elles sont fonctionnelles sur cet environnement.

Le reste se fait assez organiquement, en autant que tout le monde est d'accord que tout ce qui n'est pas dans le système de gestion de tâches ne sera pas fait, ceci assure une transparence du travail qui est fait.

Pour le reste, ça dépend vraiment du projet.

**Comment by yanic1665** [comment]
@alberto56  Merci. Je pense que ça fait une bonne basse. Je fais y ajouer quelques éléments tirés de la liste des tâches complétées dans le présent projet. Je ne pense pas pouvoir mettre au propre une telle liste à court terme, mais je vais vais sauvegarder une ébauche. Je te tiendrai au courant.
