### ISSUE TITLE
Convenir des modalités de soutien technique de la part du développeur pour la suite des choses

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#64]

**Comment by alberto56** [comment]
Le plus simple est que je continue à monitorer les billets github; toute question, ou changement mineur, je pourrai faire jusqu'au 14 avril 2021. Si c'est des modifs importantes, on pourra s'entendre sur un plan de service, sinon c'est inclus.

**Comment by yanic1665** [comment]
@alberto56  OK, merci!

**Comment by yanic1665** [comment]
@alberto56  Une question dans le cas où on décidait finalement d"ajouter une page Actualités  plus tard dans l'année (comme on l'imaginait idéalement): 1. la page existe-t-elle toujours (de façon "cachée"?  2. Serait-ce considéré comme un changement "mineur" ou un ajout hors-forfait?

**Comment by alberto56** [comment]
Ce serait un changement mineur. Ça existe encore mais caché.

**Comment by yanic1665** [comment]
@alberto56 OK. C'est l'idéal pour nous.
