### ISSUE TITLE
Repointage vers le nouveau service d'hébergement

### ISSUE THREAD

**Issue by christianArcand** [aphcq-association/site-web#65]
Salut Albert,

En relisant notre documentation, et suite au courriel que je t'ai envoyé, je me demandais comment rediriger ou repointer l'adresse aphcq.ca vers le nouvel hébergement. S'agit-il de github?

**Comment by alberto56** [comment]
Bonjour Christian,

Je n'ai pas reçu de courriel.

Actuellement, le nom de domaine aphcq.ca dirige vers l'hébergement GitHub, c'est là où est hébergé votre site web.

Vous n'avez pas besoin de service d'hébergement autre que GitHub, car GitHub est un hébergement gratuit.

**Comment by christianArcand** [comment]
ok, je l'ai envoyé à reforestation.net... Bon dans tout les cas, je recopie le contenu ici, question que tu puisses mieux comprendre...
J'ai besoin de régler un problème avec le site de l'APHCQ. 

Ma présidente m'a signalé ce matin que aphcq.ca s'est tourné en page 'under construction'.

J'ai rapidement appelé aztus, qui gère toujours le nom de domaine. (J'avais déjà réglé le renouvèlement, mais la date officiel d'échéance est le 18 avril) Le service technque m'a indiqué que le site, même s'il n'est plus hébergé par aztus, pointe toujours vers aztus. Donc, le 18 avril, cette fonction a cessé de façon automatique. Pour régler le problème, il faut s'assurer que aphcq.ca pointe vers le nouveau service d'hébergement... là-dessus, je ne sais pas vraiment comment faire. C'est là-dessus que j'aurais besoin de ton aide.

En attendant, j'ai réussi à obtenir à permettre l'affichage, à nouveau, mais pour 24 heures seulement.

Tu peux m'appeler ou m'expliquer comment faire
514-799-5633

**Comment by christianArcand** [comment]
En gros, il faut "repointer" vers le nouvel hébergement

**Comment by christianArcand** [comment]
Désolé d'insister Albert, je ne m'y connais pas beaucoup... Probablement que je peux le faire moi-même, mais je crois que c'est en passant par aztus... est-ce que l'adresse de l'aphcq est bel et bien le suivant: https://github.com/aphcq-association/site-web.git

**Comment by alberto56** [comment]
Salut Christian:

* Selon https://www.websiteplanet.com/webtools/check-domain/?domain=aphcq.ca votre domaine expire April 18, 2024 19:48:43
* L'hébergement est sur GitHub pages, c'est à jour et fonctionnel, et gratuit.
* Votre nom de domaine pointe vers GitHub pages:

```
$ dig www.aphcq.ca|grep CNAME
www.aphcq.ca.		900	IN	CNAME	aphcq-association.github.io.

```


Conclusion: vous n'avez rien à faire, tout sera fonctionnel jusqu'à 18 avril, 2024, 19:48:43!

Si vous changez l'hébergement, votre site va briser.

**Comment by christianArcand** [comment]
Merci Albert! Je te rassure, il n'est pas question de changer d'hébergement, mais surtout d'éviter de retrouver la note que notre site est en reconstruction, j'imagine que le problème vient d'aztus.

![176875618_468059164523500_4571189726939879804_n](https://user-images.githubusercontent.com/62614967/115638798-0f1f8f80-a2e1-11eb-89f1-caafc24a4eb6.png)

**Comment by alberto56** [comment]
Voici ce que je crois qui est arrivé: vous n'avez pas renouvelé à temps votre nom de domaine chez Aztus, et donc ils ont arrêté de pointer votre nom de domaine vers votre site hébergé sur GitHub. Dès que vous avez payé, ils ont recommencé à pointer le nom de domaine vers GitHub, jusqu'en avril 2024.

Je vous recommande de mettre votre domaine en mode "auto-renouvellement" pour éviter qu'il ne brise encore en 2024. J'avoue que c'est déconcertant, toutefois je vous assure, vous n'aurez rien à faire jusque là!

je vais fermer ce ticket. N'hésitez pas à me contacter s'il vous faut autre chose.

**Comment by christianArcand** [comment]
Merci beaucoup Albert. J'ai rappelé aujourd'hui, pour m'assurer qu'il n'y aurait pas d'autres soucis. Pour l'option d'auto-renouvellement, ça semble un peu compliqué pour eux de le faire, je ferai donc un rappel pour la personne contact de l'APHCQ...en 2024 de s'assurer que ça se passe bien.  :)

**Comment by alberto56** [comment]
OK! N'hésitez pas à me contacter si vous avez besoin d'autre chose.

Cordialement,

Albert
