### ISSUE TITLE
Bonjour Albert! Nous avons un nouvel administrateur pour l'APHCQ

### ISSUE THREAD

**Issue by christianArcand** [aphcq-association/site-web#67]
Salut Albert!

Juste pour t'introduire à David Boutin, nouvel administrateur. Je suis en train de l'introduire aux bases de l'admin. Il s'occupera des mises-à-jour.
Il s'est créer un compte github. 

Mais j'ai une petite question, besoin d'un rappel, à quel endroit doit-il se rendre pour entrer dans l'administration de site?
Merci d'avance,

Christian

**Comment by alberto56** [comment]
Bonjour Christian, 

Une fois que David Boutin aura son compte Github, il faut l'ajouter au projet, en allant au https://github.com/aphcq-association/site-web/settings/access

Ensuite il sera possible pour lui d'accéder au site en allant au https://www.aphcq.ca/admin/#/
