### ISSUE TITLE
Documenter ce qui sera différent dans la structure du site actuel (http://aphcq.ca) -- plan du site et textes

### ISSUE THREAD

**Issue by yanic1665** [aphcq-association/site-web#7]
Un premier travail été fait dans le document "Énoncé des besoins pour la refote du site web de l'APHCQ", qui contient un tableau comparaant les secitons de l'ancien site et celels souahitées pour le noueau site. Les changements  souhaités (ajouts, retraits, modifications) y sont soulignés au jaune. En ligne: https://docs.google.com/document/d/1z2adBb_pP3VHOmYoroAZ_yNnyKDxzs32seWuP-TqIg0/edit

**Comment by yanic1665** [comment]
Je pensais pourvoir fourir les nouveaux textes pour les pages du site avant la réunion de demain (11 mars), mais ce ne sera pas possible finalement. Est-ce l'utilisaiton des textes de l'ancien site peut-être une solution en attendant pour te permettre d'avancer et nous permettre de visualiser le tout, ou bien est-ce que dédoublerait inutilement le travail?

**Comment by alberto56** [comment]
@yanicviau non ce n'est pas plus de travail. Pas de problème.

**Comment by alberto56** [comment]
Cette tâche est désuete, le tout étant déjà documenté, je ferme.
