### ISSUE TITLE
Faire un clone de l'ancien site pour qu'on puisse changer le CNAME déjà.

### ISSUE THREAD

**Issue by alberto56** [aphcq-association/site-web#8]
Le clone est au https://aphcq-association.github.io/aphcq-avant-2020/?a=7

toutefois il y a des problèmes avec l'encodage (accents), donc je laisse dans "en cours".

Le code est au https://github.com/aphcq-association/aphcq-avant-2020

**Comment by alberto56** [comment]
OK l'encodage est réglé, je mets à "fini".

https://aphcq-association.github.io/aphcq-avant-2020/

**Comment by yanicviau** [comment]
Mon collègue Chrisitan a réussi a mettre à jour la page d'accueil l'ancien site afid 'informer les membres de l'annulaiton du congrès et cette mise è jour est bien visible en ligne. Est-ce è dire que la rediredction du nom de domaine vers le clone de l'ancien site si Githib n'a pas fonctionné?
